services:
  # ---------- Gateway ----------
  gateway-service:
    image: apotekly-gateway-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/gateway/Dockerfile.app
    container_name: ${GATEWAY_SERVICE_HOST}
    ports:
      - ${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${GATEWAY_SERVICE_HOST}
      - SERVER_HOST=${GATEWAY_SERVICE_HOST}
      - SERVER_PORT=${GATEWAY_SERVICE_PORT}
      - SERVER_TIMEOUT_READ=${GATEWAY_SERVICE_TIMEOUT_READ}
      - SERVER_TIMEOUT_WRITE=${GATEWAY_SERVICE_TIMEOUT_WRITE}
      - SERVER_TIMEOUT_SHUTDOWN=${GATEWAY_SERVICE_TIMEOUT_SHUTDOWN}
      - SERVICE_AUTH_NAME=${AUTH_SERVICE_HOST}
      - SERVICE_AUTH_HOST=${AUTH_SERVICE_HOST}
      - SERVICE_AUTH_PORT=${AUTH_SERVICE_PORT}
      - SERVICE_USER_NAME=${USER_SERVICE_HOST}
      - SERVICE_USER_HOST=${USER_SERVICE_HOST}
      - SERVICE_USER_PORT=${USER_SERVICE_PORT}
      - JWT_SECRET=${AUTH_JWT_SECRET}
    depends_on:
      jaeger:
        condition: service_started
      auth-service:
        condition: service_started
      pharmacy-service:
        condition: service_started
      user-service:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://${GATEWAY_SERVICE_HOST}:${GATEWAY_SERVICE_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ---------- Auth ----------
  auth-service:
    image: apotekly-auth-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/auth/Dockerfile.app
    container_name: ${AUTH_SERVICE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${AUTH_SERVICE_HOST}
      - SERVER_HOST=${AUTH_SERVICE_HOST}
      - SERVER_PORT=${AUTH_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${AUTH_SERVICE_TIMEOUT_SHUTDOWN}
      - DATABASE_HOST=${AUTH_DATABASE_HOST}
      - DATABASE_PORT=${AUTH_DATABASE_PORT}
      - DATABASE_USER=${AUTH_DATABASE_USER}
      - DATABASE_PASS=${AUTH_DATABASE_PASS}
      - DATABASE_NAME=${AUTH_DATABASE_NAME}
      - DATABASE_SSL_MODE=${AUTH_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${AUTH_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${AUTH_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${AUTH_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${AUTH_DATABASE_MAX_CONN_IDLE_TIME}
      - CACHE_HOST=${AUTH_CACHE_HOST}
      - CACHE_PORT=${AUTH_CACHE_PORT}
      - CACHE_PASS=${AUTH_CACHE_PASS}
      - CACHE_POOL_SIZE=${AUTH_CACHE_POOL_SIZE}
      - CACHE_MIN_IDLE_CONNS=${AUTH_CACHE_MIN_IDLE_CONNS}
      - CACHE_MAX_ACTIVE_CONNS=${AUTH_CACHE_MAX_ACTIVE_CONNS}
      - CACHE_CONN_MAX_LIFETIME=${AUTH_CACHE_CONN_MAX_LIFETIME}
      - CACHE_CONN_MAX_IDLE_TIME=${AUTH_CACHE_CONN_MAX_IDLE_TIME}
      - CACHE_TIMEOUT_DIAL=${AUTH_CACHE_TIMEOUT_DIAL}
      - CACHE_TIMEOUT_READ=${AUTH_CACHE_TIMEOUT_READ}
      - CACHE_TIMEOUT_WRITE=${AUTH_CACHE_TIMEOUT_WRITE}
    depends_on:
      auth-database:
        condition: service_healthy
      auth-migrator:
        condition: service_completed_successfully
      auth-cache:
        condition: service_healthy
  
  auth-database:
    image: postgres:16-alpine
    container_name: ${AUTH_DATABASE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASS}
      - POSTGRES_DB=${AUTH_DATABASE_NAME}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DATABASE_USER} -d ${AUTH_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

  auth-migrator:
    image: apotekly-auth-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/auth/Dockerfile.migrator
    container_name: auth-migrator
    networks:
      - apotekly-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${AUTH_DATABASE_HOST}
      - DATABASE_PORT=${AUTH_DATABASE_PORT}
      - DATABASE_USER=${AUTH_DATABASE_USER}
      - DATABASE_PASS=${AUTH_DATABASE_PASS}
      - DATABASE_NAME=${AUTH_DATABASE_NAME}
      - DATABASE_SSL_MODE=${AUTH_DATABASE_SSL_MODE}
    depends_on:
      auth-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${AUTH_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  auth-cache:
    image: redis:7.4-alpine
    container_name: ${AUTH_CACHE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass "${AUTH_CACHE_PASS}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${AUTH_CACHE_PASS}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # ---------- Notification ----------
  notification-service:
    image: apotekly-notification-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/notification/Dockerfile.app
    container_name: ${NOTIFICATION_SERVICE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${NOTIFICATION_SERVICE_HOST}
      - DATABASE_HOST=${NOTIFICATION_DATABASE_HOST}
      - DATABASE_PORT=${NOTIFICATION_DATABASE_PORT}
      - DATABASE_USER=${NOTIFICATION_DATABASE_USER}
      - DATABASE_PASS=${NOTIFICATION_DATABASE_PASS}
      - DATABASE_NAME=${NOTIFICATION_DATABASE_NAME}
      - DATABASE_SSL_MODE=${NOTIFICATION_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${NOTIFICATION_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${NOTIFICATION_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${NOTIFICATION_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${NOTIFICATION_DATABASE_MAX_CONN_IDLE_TIME}
    depends_on:
      notification-database:
        condition: service_healthy
      notification-migrator:
        condition: service_completed_successfully

  notification-database:
    image: postgres:16-alpine
    container_name: ${NOTIFICATION_DATABASE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${NOTIFICATION_DATABASE_USER}
      - POSTGRES_PASSWORD=${NOTIFICATION_DATABASE_PASS}
      - POSTGRES_DB=${NOTIFICATION_DATABASE_NAME}
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NOTIFICATION_DATABASE_USER} -d ${NOTIFICATION_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

  notification-migrator:
    image: apotekly-notification-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/notification/Dockerfile.migrator
    container_name: notification-migrator
    networks:
      - apotekly-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${NOTIFICATION_DATABASE_HOST}
      - DATABASE_PORT=${NOTIFICATION_DATABASE_PORT}
      - DATABASE_USER=${NOTIFICATION_DATABASE_USER}
      - DATABASE_PASS=${NOTIFICATION_DATABASE_PASS}
      - DATABASE_NAME=${NOTIFICATION_DATABASE_NAME}
      - DATABASE_SSL_MODE=${NOTIFICATION_DATABASE_SSL_MODE}
    depends_on:
      notification-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${NOTIFICATION_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  # ---------- Pharmacy ----------
  pharmacy-service:
    image: apotekly-pharmacy-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/pharmacy/Dockerfile.app
    container_name: ${PHARMACY_SERVICE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${PHARMACY_SERVICE_HOST}
      - SERVER_HOST=${PHARMACY_SERVICE_HOST}
      - SERVER_PORT=${PHARMACY_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${PHARMACY_SERVICE_TIMEOUT_SHUTDOWN}
      - DATABASE_HOST=${PHARMACY_DATABASE_HOST}
      - DATABASE_PORT=${PHARMACY_DATABASE_PORT}
      - DATABASE_USER=${PHARMACY_DATABASE_USER}
      - DATABASE_PASS=${PHARMACY_DATABASE_PASS}
      - DATABASE_NAME=${PHARMACY_DATABASE_NAME}
      - DATABASE_SSL_MODE=${PHARMACY_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${PHARMACY_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${PHARMACY_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${PHARMACY_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${PHARMACY_DATABASE_MAX_CONN_IDLE_TIME}
    depends_on:
      pharmacy-database:
        condition: service_healthy
      pharmacy-migrator:
        condition: service_completed_successfully

  pharmacy-database:
    image: postgis/postgis:16-3.5-alpine
    container_name: ${PHARMACY_DATABASE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PHARMACY_DATABASE_USER}
      - POSTGRES_PASSWORD=${PHARMACY_DATABASE_PASS}
      - POSTGRES_DB=${PHARMACY_DATABASE_NAME}
    volumes:
      - pharmacy_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PHARMACY_DATABASE_USER} -d ${PHARMACY_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

  pharmacy-migrator:
    image: apotekly-pharmacy-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/pharmacy/Dockerfile.migrator
    container_name: pharmacy-migrator
    networks:
      - apotekly-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${PHARMACY_DATABASE_HOST}
      - DATABASE_PORT=${PHARMACY_DATABASE_PORT}
      - DATABASE_USER=${PHARMACY_DATABASE_USER}
      - DATABASE_PASS=${PHARMACY_DATABASE_PASS}
      - DATABASE_NAME=${PHARMACY_DATABASE_NAME}
      - DATABASE_SSL_MODE=${PHARMACY_DATABASE_SSL_MODE}
    depends_on:
      pharmacy-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${PHARMACY_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  # ---------- Product ----------
  product-database:
    image: postgres:16-alpine
    container_name: ${PRODUCT_DATABASE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PRODUCT_DATABASE_USER}
      - POSTGRES_PASSWORD=${PRODUCT_DATABASE_PASS}
      - POSTGRES_DB=${PRODUCT_DATABASE_NAME}
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCT_DATABASE_USER} -d ${PRODUCT_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

  product-migrator:
    image: apotekly-product-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/product/Dockerfile.migrator
    container_name: product-migrator
    networks:
      - apotekly-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${PRODUCT_DATABASE_HOST}
      - DATABASE_PORT=${PRODUCT_DATABASE_PORT}
      - DATABASE_USER=${PRODUCT_DATABASE_USER}
      - DATABASE_PASS=${PRODUCT_DATABASE_PASS}
      - DATABASE_NAME=${PRODUCT_DATABASE_NAME}
      - DATABASE_SSL_MODE=${PRODUCT_DATABASE_SSL_MODE}
    depends_on:
      product-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${PRODUCT_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  # ---------- User ----------
  user-service:
    image: apotekly-user-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/user/Dockerfile.app
    container_name: ${USER_SERVICE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_NAME=${USER_SERVICE_HOST}
      - SERVER_HOST=${USER_SERVICE_HOST}
      - SERVER_PORT=${USER_SERVICE_PORT}
      - SERVER_TIMEOUT_SHUTDOWN=${USER_SERVICE_TIMEOUT_SHUTDOWN}
      - DATABASE_HOST=${USER_DATABASE_HOST}
      - DATABASE_PORT=${USER_DATABASE_PORT}
      - DATABASE_USER=${USER_DATABASE_USER}
      - DATABASE_PASS=${USER_DATABASE_PASS}
      - DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_SSL_MODE=${USER_DATABASE_SSL_MODE}
      - DATABASE_MAX_CONNS=${USER_DATABASE_MAX_CONNS}
      - DATABASE_MIN_CONNS=${USER_DATABASE_MIN_CONNS}
      - DATABASE_MAX_CONN_LIFETIME=${USER_DATABASE_MAX_CONN_LIFETIME}
      - DATABASE_MAX_CONN_IDLE_TIME=${USER_DATABASE_MAX_CONN_IDLE_TIME}
    depends_on:
      user-database:
        condition: service_healthy
      user-migrator:
        condition: service_completed_successfully

  user-database:
    image: postgis/postgis:16-3.5-alpine
    container_name: ${USER_DATABASE_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER_DATABASE_USER}
      - POSTGRES_PASSWORD=${USER_DATABASE_PASS}
      - POSTGRES_DB=${USER_DATABASE_NAME}
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DATABASE_USER} -d ${USER_DATABASE_NAME}"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s

  user-migrator:
    image: apotekly-user-migrator
    platform: linux/amd64
    build:
      context: .
      dockerfile: services/user/Dockerfile.migrator
    container_name: user-migrator
    networks:
      - apotekly-net
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_HOST=${USER_DATABASE_HOST}
      - DATABASE_PORT=${USER_DATABASE_PORT}
      - DATABASE_USER=${USER_DATABASE_USER}
      - DATABASE_PASS=${USER_DATABASE_PASS}
      - DATABASE_NAME=${USER_DATABASE_NAME}
      - DATABASE_SSL_MODE=${USER_DATABASE_SSL_MODE}
    depends_on:
      user-database:
        condition: service_healthy
    entrypoint: ["./bin/migrator"]
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "${USER_DATABASE_HOST}"]
      interval: 10s
      retries: 3

  # ---------- Kafka ----------
  kafka-init:
    image: apache/kafka:3.8.0
    container_name: kafka-init
    networks:
      - apotekly-net
    restart: "no"
    volumes:
      - ./scripts/create-kafka-topics.sh:/create-kafka-topics.sh
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: ["bash", "/create-kafka-topics.sh", "&&", "exit"]
  
  kafka1:
    image: apache/kafka:3.8.0
    container_name: ${BROKER_1_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${BROKER_1_HOST}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${BROKER_1_HOST}:9093,2@${BROKER_2_HOST}:9093,3@${BROKER_3_HOST}:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: ${BROKER_RANDOM_STABLE_ID}
    volumes:
      - kafka1_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "${BROKER_1_HOST}", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kafka2:
    image: apache/kafka:3.8.0
    container_name: ${BROKER_2_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${BROKER_2_HOST}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${BROKER_1_HOST}:9093,2@${BROKER_2_HOST}:9093,3@${BROKER_3_HOST}:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: ${BROKER_RANDOM_STABLE_ID}
    volumes:
      - kafka2_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "${BROKER_2_HOST}", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kafka3:
    image: apache/kafka:3.8.0
    container_name: ${BROKER_3_HOST}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${BROKER_3_HOST}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${BROKER_1_HOST}:9093,2@${BROKER_2_HOST}:9093,3@${BROKER_3_HOST}:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CLUSTER_ID: ${BROKER_RANDOM_STABLE_ID}
    volumes:
      - kafka3_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "${BROKER_3_HOST}", "9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------- Jaeger ----------
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: ${TRACER_HOST}
    ports:
      - ${TRACER_PORT}:${TRACER_PORT}
      - ${TRACER_WEB_UI_PORT}:${TRACER_WEB_UI_PORT}
    networks:
      - apotekly-net
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  apotekly-net:
    name: apotekly-net
    driver: bridge

volumes:
  auth_db_data:
  notification_db_data:
  pharmacy_db_data:
  product_db_data:
  user_db_data:
  kafka1_data:
  kafka2_data:
  kafka3_data:
