// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/auth_event.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthCreated struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthId            uint64                 `protobuf:"varint,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Email             string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role              string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	EmailVerifiedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=email_verified_at,json=emailVerifiedAt,proto3" json:"email_verified_at,omitempty"`
	Session           *string                `protobuf:"bytes,6,opt,name=session,proto3,oneof" json:"session,omitempty"`
	VerificationToken *string                `protobuf:"bytes,7,opt,name=verification_token,json=verificationToken,proto3,oneof" json:"verification_token,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthCreated) Reset() {
	*x = AuthCreated{}
	mi := &file_v1_auth_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCreated) ProtoMessage() {}

func (x *AuthCreated) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCreated.ProtoReflect.Descriptor instead.
func (*AuthCreated) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{0}
}

func (x *AuthCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthCreated) GetAuthId() uint64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *AuthCreated) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthCreated) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthCreated) GetEmailVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmailVerifiedAt
	}
	return nil
}

func (x *AuthCreated) GetSession() string {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return ""
}

func (x *AuthCreated) GetVerificationToken() string {
	if x != nil && x.VerificationToken != nil {
		return *x.VerificationToken
	}
	return ""
}

func (x *AuthCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthEmailChangeRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthId        uint64                 `protobuf:"varint,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	OldEmail      string                 `protobuf:"bytes,3,opt,name=old_email,json=oldEmail,proto3" json:"old_email,omitempty"`
	NewEmail      string                 `protobuf:"bytes,4,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEmailChangeRequested) Reset() {
	*x = AuthEmailChangeRequested{}
	mi := &file_v1_auth_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEmailChangeRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmailChangeRequested) ProtoMessage() {}

func (x *AuthEmailChangeRequested) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmailChangeRequested.ProtoReflect.Descriptor instead.
func (*AuthEmailChangeRequested) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{1}
}

func (x *AuthEmailChangeRequested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthEmailChangeRequested) GetAuthId() uint64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *AuthEmailChangeRequested) GetOldEmail() string {
	if x != nil {
		return x.OldEmail
	}
	return ""
}

func (x *AuthEmailChangeRequested) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *AuthEmailChangeRequested) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthEmailChangeRequested) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthEmailChangeRequested) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthEmailVerificationRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthId        uint64                 `protobuf:"varint,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEmailVerificationRequested) Reset() {
	*x = AuthEmailVerificationRequested{}
	mi := &file_v1_auth_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEmailVerificationRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmailVerificationRequested) ProtoMessage() {}

func (x *AuthEmailVerificationRequested) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmailVerificationRequested.ProtoReflect.Descriptor instead.
func (*AuthEmailVerificationRequested) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{2}
}

func (x *AuthEmailVerificationRequested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthEmailVerificationRequested) GetAuthId() uint64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *AuthEmailVerificationRequested) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthEmailVerificationRequested) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthEmailVerificationRequested) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthEmailVerificationRequested) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type AuthPasswordResetRequested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthId        uint64                 `protobuf:"varint,2,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthPasswordResetRequested) Reset() {
	*x = AuthPasswordResetRequested{}
	mi := &file_v1_auth_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthPasswordResetRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthPasswordResetRequested) ProtoMessage() {}

func (x *AuthPasswordResetRequested) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthPasswordResetRequested.ProtoReflect.Descriptor instead.
func (*AuthPasswordResetRequested) Descriptor() ([]byte, []int) {
	return file_v1_auth_event_proto_rawDescGZIP(), []int{3}
}

func (x *AuthPasswordResetRequested) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthPasswordResetRequested) GetAuthId() uint64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *AuthPasswordResetRequested) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthPasswordResetRequested) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AuthPasswordResetRequested) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthPasswordResetRequested) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_auth_event_proto protoreflect.FileDescriptor

const file_v1_auth_event_proto_rawDesc = "" +
	"\n" +
	"\x13v1/auth_event.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\vAuthCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\x04R\x06authId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12F\n" +
	"\x11email_verified_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0femailVerifiedAt\x12\x1d\n" +
	"\asession\x18\x06 \x01(\tH\x00R\asession\x88\x01\x01\x122\n" +
	"\x12verification_token\x18\a \x01(\tH\x01R\x11verificationToken\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\n" +
	"\n" +
	"\b_sessionB\x15\n" +
	"\x13_verification_token\"\xe2\x01\n" +
	"\x18AuthEmailChangeRequested\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\x04R\x06authId\x12\x1b\n" +
	"\told_email\x18\x03 \x01(\tR\boldEmail\x12\x1b\n" +
	"\tnew_email\x18\x04 \x01(\tR\bnewEmail\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc4\x01\n" +
	"\x1eAuthEmailVerificationRequested\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\x04R\x06authId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc0\x01\n" +
	"\x1aAuthPasswordResetRequested\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aauth_id\x18\x02 \x01(\x04R\x06authId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBNZLgithub.com/ritchieridanko/apotekly/services/shared/contract/events/v1;eventsb\x06proto3"

var (
	file_v1_auth_event_proto_rawDescOnce sync.Once
	file_v1_auth_event_proto_rawDescData []byte
)

func file_v1_auth_event_proto_rawDescGZIP() []byte {
	file_v1_auth_event_proto_rawDescOnce.Do(func() {
		file_v1_auth_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)))
	})
	return file_v1_auth_event_proto_rawDescData
}

var file_v1_auth_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_auth_event_proto_goTypes = []any{
	(*AuthCreated)(nil),                    // 0: auth.v1.AuthCreated
	(*AuthEmailChangeRequested)(nil),       // 1: auth.v1.AuthEmailChangeRequested
	(*AuthEmailVerificationRequested)(nil), // 2: auth.v1.AuthEmailVerificationRequested
	(*AuthPasswordResetRequested)(nil),     // 3: auth.v1.AuthPasswordResetRequested
	(*timestamppb.Timestamp)(nil),          // 4: google.protobuf.Timestamp
}
var file_v1_auth_event_proto_depIdxs = []int32{
	4, // 0: auth.v1.AuthCreated.email_verified_at:type_name -> google.protobuf.Timestamp
	4, // 1: auth.v1.AuthCreated.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: auth.v1.AuthEmailChangeRequested.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: auth.v1.AuthEmailVerificationRequested.created_at:type_name -> google.protobuf.Timestamp
	4, // 4: auth.v1.AuthPasswordResetRequested.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_auth_event_proto_init() }
func file_v1_auth_event_proto_init() {
	if File_v1_auth_event_proto != nil {
		return
	}
	file_v1_auth_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_event_proto_rawDesc), len(file_v1_auth_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_auth_event_proto_goTypes,
		DependencyIndexes: file_v1_auth_event_proto_depIdxs,
		MessageInfos:      file_v1_auth_event_proto_msgTypes,
	}.Build()
	File_v1_auth_event_proto = out.File
	file_v1_auth_event_proto_goTypes = nil
	file_v1_auth_event_proto_depIdxs = nil
}
