app:
  name: "auth-service"

auth:
  bcrypt:
    cost: 10
  jwt:
    issuer: "apotekly"
    secret: ""
    duration: "10m"
  duration:
    session: "24h"
    verification: "24h"

server:
  host: "localhost"
  port: 50051
  timeout:
    shutdown: "10s"

database:
  host: "localhost"
  port: 5432
  user: ""
  pass: ""
  name: "apotekly_auth_db"
  ssl_mode: "disable"
  max_conns: 5
  min_conns: 1
  max_conn_lifetime: "1h"
  max_conn_idle_time: "30m"

cache:
  host: "localhost"
  port: 6379
  pass: ""
  pool_size: 5
  min_idle_conns: 1
  max_active_conns: 10
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"
  timeout:
    dial: "5s"
    read: "1s"
    write: "1s"

tracer:
  host: "localhost"
  port: 4317

broker:
  brokers: "localhost:9092,localhost:9093,localhost:9094"
  ac:
    name: "auth.created"
    balancer: "murmur2"
    batch_size: 1
    batch_timeout: "5ms"
