syntax = "proto3";

package auth.v1;

import "google/protobuf/empty.proto";

option go_package = "github.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apis";

service AuthService {
  rpc SignUp (SignUpRequest) returns (SignUpResponse);
  rpc SignIn (SignInRequest) returns (SignInResponse);
  rpc SignOut (SignOutRequest) returns (google.protobuf.Empty);
  rpc IsEmailAvailable (IsEmailAvailableRequest) returns (IsEmailAvailableResponse);
  rpc RotateAuthToken (RotateAuthTokenRequest) returns (RotateAuthTokenResponse);
  rpc ResendVerification (google.protobuf.Empty) returns (ResendVerificationResponse);
  rpc VerifyEmail (VerifyEmailRequest) returns (VerifyEmailResponse);
}

message Auth {
  string email = 1;
  string role = 2;
  bool is_email_verified = 3;
}

message AccessToken {
  string token = 1;
  uint64 expires_in_seconds = 2;
}

message RefreshToken {
  string token = 1;
  uint64 expires_in_seconds = 2;
}

message AuthToken {
  AccessToken access_token = 1;
  RefreshToken refresh_token = 2;
}

message SignUpRequest {
  string email = 1;
  string password = 2;
}

message SignUpResponse {
  Auth auth = 1;
  AuthToken auth_token = 2;
}

message SignInRequest {
  string email = 1;
  string password = 2;
}

message SignInResponse {
  Auth auth = 1;
  AuthToken auth_token = 2;
}

message SignOutRequest {
  string refresh_token = 1;
}

message IsEmailAvailableRequest {
  string email = 1;
}

message IsEmailAvailableResponse {
  bool is_available = 1;
}

message RotateAuthTokenRequest {
  string refresh_token = 1;
}

message RotateAuthTokenResponse {
  AuthToken auth_token = 1;
}

message ResendVerificationResponse {
  string email = 1;
}

message VerifyEmailRequest {
  string refresh_token = 1;
  string verification_token = 2;
}

message VerifyEmailResponse {
  Auth auth = 1;
  AuthToken auth_token = 2;
}
