syntax = "proto3";

package auth.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/ritchieridanko/apotekly/services/shared/contract/events/v1;events";

message AuthCreated {
  string id = 1;
  uint64 auth_id = 2;
  string email = 3;
  string role = 4;
  google.protobuf.Timestamp email_verified_at = 5;
  optional string session = 6;
  optional string verification_token = 7;
  google.protobuf.Timestamp created_at = 8;
}

message AuthEmailChangeRequested {
  string id = 1;
  uint64 auth_id = 2;
  string old_email = 3;
  string new_email = 4;
  string role = 5;
  string token = 6;
  google.protobuf.Timestamp created_at = 7;
}

message AuthEmailVerificationRequested {
  string id = 1;
  uint64 auth_id = 2;
  string email = 3;
  string role = 4;
  string token = 5;
  google.protobuf.Timestamp created_at = 6;
}
