syntax = "proto3";

package pharmacy.v1;

import "v1/sorter.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apis";

service PharmacyService {
  rpc CreatePharmacy (CreatePharmacyRequest) returns (CreatePharmacyResponse);
  rpc GetMe (google.protobuf.Empty) returns (PharmacyGetMeResponse);
  rpc GetID (PharmacyGetIDRequest) returns (PharmacyGetIDResponse);
  rpc GetActiveStatus (PharmacyGetActiveStatusRequest) returns (PharmacyGetActiveStatusResponse);
  rpc GetPharmacyByID (GetPharmacyByIDRequest) returns (GetPharmacyByIDResponse);
  rpc GetAllPharmacies (GetAllPharmaciesRequest) returns (GetAllPharmaciesResponse);
  rpc UpdatePharmacy (UpdatePharmacyRequest) returns (UpdatePharmacyResponse);
  rpc UpdateProfilePicture (PharmacyUpdateProfilePictureRequest) returns (PharmacyUpdateProfilePictureResponse);
  rpc UpdateProfileBanner (PharmacyUpdateProfileBannerRequest) returns (PharmacyUpdateProfileBannerResponse);
}

message Pharmacy {
  string id = 1;
  string name = 2;
  optional string legal_name = 3;
  optional string description = 4;
  string status = 5;
  optional bytes online_hours = 6;
  string country = 7;
  optional string subdivision_1 = 8;
  optional string subdivision_2 = 9;
  optional string subdivision_3 = 10;
  optional string subdivision_4 = 11;
  string street = 12;
  string postal_code = 13;
  double latitude = 14;
  double longitude = 15;
  optional string email = 16;
  optional string phone = 17;
  optional string website = 18;
  optional string whatsapp = 19;
  optional string profile_picture = 20;
  optional string profile_banner = 21;
  google.protobuf.Timestamp verified_at = 22;
	google.protobuf.Timestamp created_at = 23;
	google.protobuf.Timestamp updated_at = 24;
}

message PharmacySummary {
  string id = 1;
  string name = 2;
  optional string legal_name = 3;
  optional bytes online_hours = 4;
  optional string profile_picture = 5;
  optional double distance_m = 6;
  google.protobuf.Timestamp created_at = 7;
	google.protobuf.Timestamp updated_at = 8;
}

message CreatePharmacyRequest {
  string name = 1;
  optional string legal_name = 2;
  optional string description = 3;
  optional bytes online_hours = 4;
  string country = 5;
  optional string subdivision_1 = 6;
  optional string subdivision_2 = 7;
  optional string subdivision_3 = 8;
  optional string subdivision_4 = 9;
  string street = 10;
  string postal_code = 11;
  double latitude = 12;
  double longitude = 13;
  optional string email = 14;
  optional string phone = 15;
  optional string website = 16;
  optional string whatsapp = 17;
}

message CreatePharmacyResponse {
  Pharmacy pharmacy = 1;
}

message PharmacyGetMeResponse {
  Pharmacy pharmacy = 1;
}

message PharmacyGetIDRequest {
  uint64 auth_id = 1;
}

message PharmacyGetIDResponse {
  string pharmacy_id = 1;
}

message PharmacyGetActiveStatusRequest {
  uint64 auth_id = 1;
}

message PharmacyGetActiveStatusResponse {
  bool is_active = 1;
}

message GetPharmacyByIDRequest {
  string pharmacy_id = 1;
}

message GetPharmacyByIDResponse {
  Pharmacy pharmacy = 1;
}

message GetAllPharmaciesRequest {
  // Queries
  optional string search = 1;
  optional uint32 radius_m = 2;
  optional double latitude = 3;
  optional double longitude = 4;

  // Sorters
  sorter.v1.Sorter by_location = 5;
  sorter.v1.Sorter by_created_at = 6;
  sorter.v1.Sorter by_updated_at = 7;

  // Pagination
  int32 page = 8;
  int32 page_size = 9;
}

message GetAllPharmaciesResponse {
  repeated PharmacySummary pharmacies = 1;
	int64 total = 2;
}

message UpdatePharmacyRequest {
  optional string name = 1;
  optional string legal_name = 2;
  optional string description = 3;
  optional bytes online_hours = 4;
  optional string country = 5;
  optional string subdivision_1 = 6;
  optional string subdivision_2 = 7;
  optional string subdivision_3 = 8;
  optional string subdivision_4 = 9;
  optional string street = 10;
  optional string postal_code = 11;
  optional double latitude = 12;
  optional double longitude = 13;
  optional string email = 14;
  optional string phone = 15;
  optional string website = 16;
  optional string whatsapp = 17;
}

message UpdatePharmacyResponse {
  Pharmacy pharmacy = 1;
}

message PharmacyUpdateProfilePictureRequest {
  string profile_picture_url = 1;
}

message PharmacyUpdateProfilePictureResponse {
  Pharmacy pharmacy = 1;
}

message PharmacyUpdateProfileBannerRequest {
  string profile_banner_url = 1;
}

message PharmacyUpdateProfileBannerResponse {
  Pharmacy pharmacy = 1;
}
