# ---------- Build Stage ----------
FROM golang:1.25.0-alpine3.22 AS builder

# Install build dependencies
RUN apk add --no-cache git

# Set work directory
WORKDIR /app/user

# Copy and download app dependencies
COPY services/shared/go.mod services/shared/go.sum ../shared/
COPY services/user/go.mod services/user/go.sum ./
RUN go mod download

# Copy app source
COPY services/shared/configs ../shared/configs
COPY services/shared/constants ../shared/constants
COPY services/shared/infra/database ../shared/infra/database
COPY services/shared/infra/logger ../shared/infra/logger
COPY services/shared/utils ../shared/utils
COPY services/user/cmd/migrator ./cmd/migrator
COPY services/user/configs ./configs
COPY services/user/migrations ./migrations

# Build binary
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o bin/migrator cmd/migrator/main.go

# ---------- Runtime Stage ----------
FROM alpine:3.22

# Set work directory
WORKDIR /root

# Copy from the Build Stage
COPY --from=builder /app/user/bin ./bin
COPY --from=builder /app/user/configs ./configs
COPY --from=builder /app/user/migrations ./migrations

# Set entry point
ENTRYPOINT ["./bin/migrator"]
