// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/auth_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Role            string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	IsEmailVerified bool                   `protobuf:"varint,3,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_v1_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Auth) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Auth) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

type AccessToken struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresInSeconds uint64                 `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_v1_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{1}
}

func (x *AccessToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AccessToken) GetExpiresInSeconds() uint64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type RefreshToken struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresInSeconds uint64                 `protobuf:"varint,2,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_v1_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshToken) GetExpiresInSeconds() uint64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *AccessToken           `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  *RefreshToken          `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_v1_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthToken) GetAccessToken() *AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *AuthToken) GetRefreshToken() *RefreshToken {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SignUpResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

type IsEmailAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEmailAvailableRequest) Reset() {
	*x = IsEmailAvailableRequest{}
	mi := &file_v1_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEmailAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEmailAvailableRequest) ProtoMessage() {}

func (x *IsEmailAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEmailAvailableRequest.ProtoReflect.Descriptor instead.
func (*IsEmailAvailableRequest) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *IsEmailAvailableRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type IsEmailAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable   bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEmailAvailableResponse) Reset() {
	*x = IsEmailAvailableResponse{}
	mi := &file_v1_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEmailAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEmailAvailableResponse) ProtoMessage() {}

func (x *IsEmailAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEmailAvailableResponse.ProtoReflect.Descriptor instead.
func (*IsEmailAvailableResponse) Descriptor() ([]byte, []int) {
	return file_v1_auth_api_proto_rawDescGZIP(), []int{7}
}

func (x *IsEmailAvailableResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

var File_v1_auth_api_proto protoreflect.FileDescriptor

const file_v1_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x11v1/auth_api.proto\x12\aauth.v1\"\\\n" +
	"\x04Auth\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12*\n" +
	"\x11is_email_verified\x18\x03 \x01(\bR\x0fisEmailVerified\"Q\n" +
	"\vAccessToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x04R\x10expiresInSeconds\"R\n" +
	"\fRefreshToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x12expires_in_seconds\x18\x02 \x01(\x04R\x10expiresInSeconds\"\x80\x01\n" +
	"\tAuthToken\x127\n" +
	"\faccess_token\x18\x01 \x01(\v2\x14.auth.v1.AccessTokenR\vaccessToken\x12:\n" +
	"\rrefresh_token\x18\x02 \x01(\v2\x15.auth.v1.RefreshTokenR\frefreshToken\"A\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"f\n" +
	"\x0eSignUpResponse\x12!\n" +
	"\x04auth\x18\x01 \x01(\v2\r.auth.v1.AuthR\x04auth\x121\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x12.auth.v1.AuthTokenR\tauthToken\"/\n" +
	"\x17IsEmailAvailableRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"=\n" +
	"\x18IsEmailAvailableResponse\x12!\n" +
	"\fis_available\x18\x01 \x01(\bR\visAvailable2\xa1\x01\n" +
	"\vAuthService\x129\n" +
	"\x06SignUp\x12\x16.auth.v1.SignUpRequest\x1a\x17.auth.v1.SignUpResponse\x12W\n" +
	"\x10IsEmailAvailable\x12 .auth.v1.IsEmailAvailableRequest\x1a!.auth.v1.IsEmailAvailableResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_auth_api_proto_rawDescOnce sync.Once
	file_v1_auth_api_proto_rawDescData []byte
)

func file_v1_auth_api_proto_rawDescGZIP() []byte {
	file_v1_auth_api_proto_rawDescOnce.Do(func() {
		file_v1_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_auth_api_proto_rawDesc), len(file_v1_auth_api_proto_rawDesc)))
	})
	return file_v1_auth_api_proto_rawDescData
}

var file_v1_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_auth_api_proto_goTypes = []any{
	(*Auth)(nil),                     // 0: auth.v1.Auth
	(*AccessToken)(nil),              // 1: auth.v1.AccessToken
	(*RefreshToken)(nil),             // 2: auth.v1.RefreshToken
	(*AuthToken)(nil),                // 3: auth.v1.AuthToken
	(*SignUpRequest)(nil),            // 4: auth.v1.SignUpRequest
	(*SignUpResponse)(nil),           // 5: auth.v1.SignUpResponse
	(*IsEmailAvailableRequest)(nil),  // 6: auth.v1.IsEmailAvailableRequest
	(*IsEmailAvailableResponse)(nil), // 7: auth.v1.IsEmailAvailableResponse
}
var file_v1_auth_api_proto_depIdxs = []int32{
	1, // 0: auth.v1.AuthToken.access_token:type_name -> auth.v1.AccessToken
	2, // 1: auth.v1.AuthToken.refresh_token:type_name -> auth.v1.RefreshToken
	0, // 2: auth.v1.SignUpResponse.auth:type_name -> auth.v1.Auth
	3, // 3: auth.v1.SignUpResponse.auth_token:type_name -> auth.v1.AuthToken
	4, // 4: auth.v1.AuthService.SignUp:input_type -> auth.v1.SignUpRequest
	6, // 5: auth.v1.AuthService.IsEmailAvailable:input_type -> auth.v1.IsEmailAvailableRequest
	5, // 6: auth.v1.AuthService.SignUp:output_type -> auth.v1.SignUpResponse
	7, // 7: auth.v1.AuthService.IsEmailAvailable:output_type -> auth.v1.IsEmailAvailableResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_auth_api_proto_init() }
func file_v1_auth_api_proto_init() {
	if File_v1_auth_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_auth_api_proto_rawDesc), len(file_v1_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_auth_api_proto_goTypes,
		DependencyIndexes: file_v1_auth_api_proto_depIdxs,
		MessageInfos:      file_v1_auth_api_proto_msgTypes,
	}.Build()
	File_v1_auth_api_proto = out.File
	file_v1_auth_api_proto_goTypes = nil
	file_v1_auth_api_proto_depIdxs = nil
}
