// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/pharmacy_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pharmacy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName      *string                `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OnlineHours    []byte                 `protobuf:"bytes,6,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	Country        string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1  *string                `protobuf:"bytes,8,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2  *string                `protobuf:"bytes,9,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3  *string                `protobuf:"bytes,10,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4  *string                `protobuf:"bytes,11,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street         string                 `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode     string                 `protobuf:"bytes,13,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude       float64                `protobuf:"fixed64,14,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,15,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Email          *string                `protobuf:"bytes,16,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone          *string                `protobuf:"bytes,17,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Website        *string                `protobuf:"bytes,18,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Whatsapp       *string                `protobuf:"bytes,19,opt,name=whatsapp,proto3,oneof" json:"whatsapp,omitempty"`
	ProfilePicture *string                `protobuf:"bytes,20,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	ProfileBanner  *string                `protobuf:"bytes,21,opt,name=profile_banner,json=profileBanner,proto3,oneof" json:"profile_banner,omitempty"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pharmacy) Reset() {
	*x = Pharmacy{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pharmacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pharmacy) ProtoMessage() {}

func (x *Pharmacy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pharmacy.ProtoReflect.Descriptor instead.
func (*Pharmacy) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{0}
}

func (x *Pharmacy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pharmacy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pharmacy) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *Pharmacy) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Pharmacy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pharmacy) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *Pharmacy) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *Pharmacy) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Pharmacy) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Pharmacy) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Pharmacy) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Pharmacy) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Pharmacy) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Pharmacy) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *Pharmacy) GetWhatsapp() string {
	if x != nil && x.Whatsapp != nil {
		return *x.Whatsapp
	}
	return ""
}

func (x *Pharmacy) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *Pharmacy) GetProfileBanner() string {
	if x != nil && x.ProfileBanner != nil {
		return *x.ProfileBanner
	}
	return ""
}

func (x *Pharmacy) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Pharmacy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Pharmacy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PharmacySummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName      *string                `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	OnlineHours    []byte                 `protobuf:"bytes,4,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	ProfilePicture *string                `protobuf:"bytes,5,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	DistanceM      *float64               `protobuf:"fixed64,6,opt,name=distance_m,json=distanceM,proto3,oneof" json:"distance_m,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PharmacySummary) Reset() {
	*x = PharmacySummary{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacySummary) ProtoMessage() {}

func (x *PharmacySummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacySummary.ProtoReflect.Descriptor instead.
func (*PharmacySummary) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{1}
}

func (x *PharmacySummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PharmacySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PharmacySummary) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *PharmacySummary) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *PharmacySummary) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *PharmacySummary) GetDistanceM() float64 {
	if x != nil && x.DistanceM != nil {
		return *x.DistanceM
	}
	return 0
}

func (x *PharmacySummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PharmacySummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePharmacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LegalName     *string                `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OnlineHours   []byte                 `protobuf:"bytes,4,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *string                `protobuf:"bytes,6,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2 *string                `protobuf:"bytes,7,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3 *string                `protobuf:"bytes,8,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4 *string                `protobuf:"bytes,9,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,10,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode    string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,13,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,15,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Website       *string                `protobuf:"bytes,16,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Whatsapp      *string                `protobuf:"bytes,17,opt,name=whatsapp,proto3,oneof" json:"whatsapp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePharmacyRequest) Reset() {
	*x = CreatePharmacyRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePharmacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePharmacyRequest) ProtoMessage() {}

func (x *CreatePharmacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePharmacyRequest.ProtoReflect.Descriptor instead.
func (*CreatePharmacyRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePharmacyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePharmacyRequest) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *CreatePharmacyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePharmacyRequest) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *CreatePharmacyRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *CreatePharmacyRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreatePharmacyRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreatePharmacyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePharmacyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreatePharmacyRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreatePharmacyRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreatePharmacyRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *CreatePharmacyRequest) GetWhatsapp() string {
	if x != nil && x.Whatsapp != nil {
		return *x.Whatsapp
	}
	return ""
}

type CreatePharmacyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePharmacyResponse) Reset() {
	*x = CreatePharmacyResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePharmacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePharmacyResponse) ProtoMessage() {}

func (x *CreatePharmacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePharmacyResponse.ProtoReflect.Descriptor instead.
func (*CreatePharmacyResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePharmacyResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

type PharmacyGetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyGetMeResponse) Reset() {
	*x = PharmacyGetMeResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyGetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyGetMeResponse) ProtoMessage() {}

func (x *PharmacyGetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyGetMeResponse.ProtoReflect.Descriptor instead.
func (*PharmacyGetMeResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{4}
}

func (x *PharmacyGetMeResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

type PharmacyGetIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthId        uint64                 `protobuf:"varint,1,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyGetIDRequest) Reset() {
	*x = PharmacyGetIDRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyGetIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyGetIDRequest) ProtoMessage() {}

func (x *PharmacyGetIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyGetIDRequest.ProtoReflect.Descriptor instead.
func (*PharmacyGetIDRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{5}
}

func (x *PharmacyGetIDRequest) GetAuthId() uint64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type PharmacyGetIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PharmacyId    string                 `protobuf:"bytes,1,opt,name=pharmacy_id,json=pharmacyId,proto3" json:"pharmacy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyGetIDResponse) Reset() {
	*x = PharmacyGetIDResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyGetIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyGetIDResponse) ProtoMessage() {}

func (x *PharmacyGetIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyGetIDResponse.ProtoReflect.Descriptor instead.
func (*PharmacyGetIDResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{6}
}

func (x *PharmacyGetIDResponse) GetPharmacyId() string {
	if x != nil {
		return x.PharmacyId
	}
	return ""
}

type GetAllPharmaciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Queries
	Search    *string  `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	RadiusM   *uint32  `protobuf:"varint,2,opt,name=radius_m,json=radiusM,proto3,oneof" json:"radius_m,omitempty"`
	Latitude  *float64 `protobuf:"fixed64,3,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude *float64 `protobuf:"fixed64,4,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	// Sorters
	ByLocation  *Sorter `protobuf:"bytes,5,opt,name=by_location,json=byLocation,proto3" json:"by_location,omitempty"`
	ByCreatedAt *Sorter `protobuf:"bytes,6,opt,name=by_created_at,json=byCreatedAt,proto3" json:"by_created_at,omitempty"`
	ByUpdatedAt *Sorter `protobuf:"bytes,7,opt,name=by_updated_at,json=byUpdatedAt,proto3" json:"by_updated_at,omitempty"`
	// Pagination
	Page          int32 `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32 `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPharmaciesRequest) Reset() {
	*x = GetAllPharmaciesRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPharmaciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPharmaciesRequest) ProtoMessage() {}

func (x *GetAllPharmaciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPharmaciesRequest.ProtoReflect.Descriptor instead.
func (*GetAllPharmaciesRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllPharmaciesRequest) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *GetAllPharmaciesRequest) GetRadiusM() uint32 {
	if x != nil && x.RadiusM != nil {
		return *x.RadiusM
	}
	return 0
}

func (x *GetAllPharmaciesRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GetAllPharmaciesRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GetAllPharmaciesRequest) GetByLocation() *Sorter {
	if x != nil {
		return x.ByLocation
	}
	return nil
}

func (x *GetAllPharmaciesRequest) GetByCreatedAt() *Sorter {
	if x != nil {
		return x.ByCreatedAt
	}
	return nil
}

func (x *GetAllPharmaciesRequest) GetByUpdatedAt() *Sorter {
	if x != nil {
		return x.ByUpdatedAt
	}
	return nil
}

func (x *GetAllPharmaciesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPharmaciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllPharmaciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacies    []*PharmacySummary     `protobuf:"bytes,1,rep,name=pharmacies,proto3" json:"pharmacies,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPharmaciesResponse) Reset() {
	*x = GetAllPharmaciesResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPharmaciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPharmaciesResponse) ProtoMessage() {}

func (x *GetAllPharmaciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPharmaciesResponse.ProtoReflect.Descriptor instead.
func (*GetAllPharmaciesResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllPharmaciesResponse) GetPharmacies() []*PharmacySummary {
	if x != nil {
		return x.Pharmacies
	}
	return nil
}

func (x *GetAllPharmaciesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdatePharmacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	LegalName     *string                `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OnlineHours   []byte                 `protobuf:"bytes,4,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	Country       *string                `protobuf:"bytes,5,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Subdivision_1 *string                `protobuf:"bytes,6,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2 *string                `protobuf:"bytes,7,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3 *string                `protobuf:"bytes,8,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4 *string                `protobuf:"bytes,9,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street        *string                `protobuf:"bytes,10,opt,name=street,proto3,oneof" json:"street,omitempty"`
	PostalCode    *string                `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,12,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,13,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,15,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Website       *string                `protobuf:"bytes,16,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Whatsapp      *string                `protobuf:"bytes,17,opt,name=whatsapp,proto3,oneof" json:"whatsapp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePharmacyRequest) Reset() {
	*x = UpdatePharmacyRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePharmacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePharmacyRequest) ProtoMessage() {}

func (x *UpdatePharmacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePharmacyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePharmacyRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePharmacyRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *UpdatePharmacyRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdatePharmacyRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *UpdatePharmacyRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *UpdatePharmacyRequest) GetWhatsapp() string {
	if x != nil && x.Whatsapp != nil {
		return *x.Whatsapp
	}
	return ""
}

type UpdatePharmacyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePharmacyResponse) Reset() {
	*x = UpdatePharmacyResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePharmacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePharmacyResponse) ProtoMessage() {}

func (x *UpdatePharmacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePharmacyResponse.ProtoReflect.Descriptor instead.
func (*UpdatePharmacyResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePharmacyResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

type PharmacyUpdateProfilePictureRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProfilePictureUrl string                 `protobuf:"bytes,1,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PharmacyUpdateProfilePictureRequest) Reset() {
	*x = PharmacyUpdateProfilePictureRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyUpdateProfilePictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyUpdateProfilePictureRequest) ProtoMessage() {}

func (x *PharmacyUpdateProfilePictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyUpdateProfilePictureRequest.ProtoReflect.Descriptor instead.
func (*PharmacyUpdateProfilePictureRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{11}
}

func (x *PharmacyUpdateProfilePictureRequest) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

type PharmacyUpdateProfilePictureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyUpdateProfilePictureResponse) Reset() {
	*x = PharmacyUpdateProfilePictureResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyUpdateProfilePictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyUpdateProfilePictureResponse) ProtoMessage() {}

func (x *PharmacyUpdateProfilePictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyUpdateProfilePictureResponse.ProtoReflect.Descriptor instead.
func (*PharmacyUpdateProfilePictureResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{12}
}

func (x *PharmacyUpdateProfilePictureResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

type PharmacyUpdateProfileBannerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProfileBannerUrl string                 `protobuf:"bytes,1,opt,name=profile_banner_url,json=profileBannerUrl,proto3" json:"profile_banner_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PharmacyUpdateProfileBannerRequest) Reset() {
	*x = PharmacyUpdateProfileBannerRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyUpdateProfileBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyUpdateProfileBannerRequest) ProtoMessage() {}

func (x *PharmacyUpdateProfileBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyUpdateProfileBannerRequest.ProtoReflect.Descriptor instead.
func (*PharmacyUpdateProfileBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{13}
}

func (x *PharmacyUpdateProfileBannerRequest) GetProfileBannerUrl() string {
	if x != nil {
		return x.ProfileBannerUrl
	}
	return ""
}

type PharmacyUpdateProfileBannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyUpdateProfileBannerResponse) Reset() {
	*x = PharmacyUpdateProfileBannerResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyUpdateProfileBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyUpdateProfileBannerResponse) ProtoMessage() {}

func (x *PharmacyUpdateProfileBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyUpdateProfileBannerResponse.ProtoReflect.Descriptor instead.
func (*PharmacyUpdateProfileBannerResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{14}
}

func (x *PharmacyUpdateProfileBannerResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

var File_v1_pharmacy_api_proto protoreflect.FileDescriptor

const file_v1_pharmacy_api_proto_rawDesc = "" +
	"\n" +
	"\x15v1/pharmacy_api.proto\x12\vpharmacy.v1\x1a\x0fv1/sorter.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\b\n" +
	"\bPharmacy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12&\n" +
	"\fonline_hours\x18\x06 \x01(\fH\x02R\vonlineHours\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\b \x01(\tH\x03R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\t \x01(\tH\x04R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\n" +
	" \x01(\tH\x05R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\v \x01(\tH\x06R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\f \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\r \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x01R\tlongitude\x12\x19\n" +
	"\x05email\x18\x10 \x01(\tH\aR\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x11 \x01(\tH\bR\x05phone\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x12 \x01(\tH\tR\awebsite\x88\x01\x01\x12\x1f\n" +
	"\bwhatsapp\x18\x13 \x01(\tH\n" +
	"R\bwhatsapp\x88\x01\x01\x12,\n" +
	"\x0fprofile_picture\x18\x14 \x01(\tH\vR\x0eprofilePicture\x88\x01\x01\x12*\n" +
	"\x0eprofile_banner\x18\x15 \x01(\tH\fR\rprofileBanner\x88\x01\x01\x12;\n" +
	"\vverified_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x129\n" +
	"\n" +
	"created_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_legal_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_online_hoursB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_websiteB\v\n" +
	"\t_whatsappB\x12\n" +
	"\x10_profile_pictureB\x11\n" +
	"\x0f_profile_banner\"\x8c\x03\n" +
	"\x0fPharmacySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12&\n" +
	"\fonline_hours\x18\x04 \x01(\fH\x01R\vonlineHours\x88\x01\x01\x12,\n" +
	"\x0fprofile_picture\x18\x05 \x01(\tH\x02R\x0eprofilePicture\x88\x01\x01\x12\"\n" +
	"\n" +
	"distance_m\x18\x06 \x01(\x01H\x03R\tdistanceM\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_legal_nameB\x0f\n" +
	"\r_online_hoursB\x12\n" +
	"\x10_profile_pictureB\r\n" +
	"\v_distance_m\"\xee\x05\n" +
	"\x15CreatePharmacyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12&\n" +
	"\fonline_hours\x18\x04 \x01(\fH\x02R\vonlineHours\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\x06 \x01(\tH\x03R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\a \x01(\tH\x04R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\b \x01(\tH\x05R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\t \x01(\tH\x06R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\n" +
	" \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\f \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\r \x01(\x01R\tlongitude\x12\x19\n" +
	"\x05email\x18\x0e \x01(\tH\aR\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x0f \x01(\tH\bR\x05phone\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x10 \x01(\tH\tR\awebsite\x88\x01\x01\x12\x1f\n" +
	"\bwhatsapp\x18\x11 \x01(\tH\n" +
	"R\bwhatsapp\x88\x01\x01B\r\n" +
	"\v_legal_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_online_hoursB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_websiteB\v\n" +
	"\t_whatsapp\"K\n" +
	"\x16CreatePharmacyResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy\"J\n" +
	"\x15PharmacyGetMeResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy\"/\n" +
	"\x14PharmacyGetIDRequest\x12\x17\n" +
	"\aauth_id\x18\x01 \x01(\x04R\x06authId\"8\n" +
	"\x15PharmacyGetIDResponse\x12\x1f\n" +
	"\vpharmacy_id\x18\x01 \x01(\tR\n" +
	"pharmacyId\"\xa0\x03\n" +
	"\x17GetAllPharmaciesRequest\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x1e\n" +
	"\bradius_m\x18\x02 \x01(\rH\x01R\aradiusM\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x03 \x01(\x01H\x02R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x04 \x01(\x01H\x03R\tlongitude\x88\x01\x01\x122\n" +
	"\vby_location\x18\x05 \x01(\v2\x11.sorter.v1.SorterR\n" +
	"byLocation\x125\n" +
	"\rby_created_at\x18\x06 \x01(\v2\x11.sorter.v1.SorterR\vbyCreatedAt\x125\n" +
	"\rby_updated_at\x18\a \x01(\v2\x11.sorter.v1.SorterR\vbyUpdatedAt\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSizeB\t\n" +
	"\a_searchB\v\n" +
	"\t_radius_mB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"n\n" +
	"\x18GetAllPharmaciesResponse\x12<\n" +
	"\n" +
	"pharmacies\x18\x01 \x03(\v2\x1c.pharmacy.v1.PharmacySummaryR\n" +
	"pharmacies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xd7\x06\n" +
	"\x15UpdatePharmacyRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\"\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tH\x01R\tlegalName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01\x12&\n" +
	"\fonline_hours\x18\x04 \x01(\fH\x03R\vonlineHours\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x05 \x01(\tH\x04R\acountry\x88\x01\x01\x12(\n" +
	"\rsubdivision_1\x18\x06 \x01(\tH\x05R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\a \x01(\tH\x06R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\b \x01(\tH\aR\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\t \x01(\tH\bR\fsubdivision4\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\n" +
	" \x01(\tH\tR\x06street\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\v \x01(\tH\n" +
	"R\n" +
	"postalCode\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\f \x01(\x01H\vR\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\r \x01(\x01H\fR\tlongitude\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x0e \x01(\tH\rR\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x0f \x01(\tH\x0eR\x05phone\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x10 \x01(\tH\x0fR\awebsite\x88\x01\x01\x12\x1f\n" +
	"\bwhatsapp\x18\x11 \x01(\tH\x10R\bwhatsapp\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_legal_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_online_hoursB\n" +
	"\n" +
	"\b_countryB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4B\t\n" +
	"\a_streetB\x0e\n" +
	"\f_postal_codeB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_websiteB\v\n" +
	"\t_whatsapp\"K\n" +
	"\x16UpdatePharmacyResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy\"U\n" +
	"#PharmacyUpdateProfilePictureRequest\x12.\n" +
	"\x13profile_picture_url\x18\x01 \x01(\tR\x11profilePictureUrl\"Y\n" +
	"$PharmacyUpdateProfilePictureResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy\"R\n" +
	"\"PharmacyUpdateProfileBannerRequest\x12,\n" +
	"\x12profile_banner_url\x18\x01 \x01(\tR\x10profileBannerUrl\"X\n" +
	"#PharmacyUpdateProfileBannerResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy2\xb4\x05\n" +
	"\x0fPharmacyService\x12Y\n" +
	"\x0eCreatePharmacy\x12\".pharmacy.v1.CreatePharmacyRequest\x1a#.pharmacy.v1.CreatePharmacyResponse\x12C\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a\".pharmacy.v1.PharmacyGetMeResponse\x12N\n" +
	"\x05GetID\x12!.pharmacy.v1.PharmacyGetIDRequest\x1a\".pharmacy.v1.PharmacyGetIDResponse\x12_\n" +
	"\x10GetAllPharmacies\x12$.pharmacy.v1.GetAllPharmaciesRequest\x1a%.pharmacy.v1.GetAllPharmaciesResponse\x12Y\n" +
	"\x0eUpdatePharmacy\x12\".pharmacy.v1.UpdatePharmacyRequest\x1a#.pharmacy.v1.UpdatePharmacyResponse\x12{\n" +
	"\x14UpdateProfilePicture\x120.pharmacy.v1.PharmacyUpdateProfilePictureRequest\x1a1.pharmacy.v1.PharmacyUpdateProfilePictureResponse\x12x\n" +
	"\x13UpdateProfileBanner\x12/.pharmacy.v1.PharmacyUpdateProfileBannerRequest\x1a0.pharmacy.v1.PharmacyUpdateProfileBannerResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_pharmacy_api_proto_rawDescOnce sync.Once
	file_v1_pharmacy_api_proto_rawDescData []byte
)

func file_v1_pharmacy_api_proto_rawDescGZIP() []byte {
	file_v1_pharmacy_api_proto_rawDescOnce.Do(func() {
		file_v1_pharmacy_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pharmacy_api_proto_rawDesc), len(file_v1_pharmacy_api_proto_rawDesc)))
	})
	return file_v1_pharmacy_api_proto_rawDescData
}

var file_v1_pharmacy_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v1_pharmacy_api_proto_goTypes = []any{
	(*Pharmacy)(nil),                             // 0: pharmacy.v1.Pharmacy
	(*PharmacySummary)(nil),                      // 1: pharmacy.v1.PharmacySummary
	(*CreatePharmacyRequest)(nil),                // 2: pharmacy.v1.CreatePharmacyRequest
	(*CreatePharmacyResponse)(nil),               // 3: pharmacy.v1.CreatePharmacyResponse
	(*PharmacyGetMeResponse)(nil),                // 4: pharmacy.v1.PharmacyGetMeResponse
	(*PharmacyGetIDRequest)(nil),                 // 5: pharmacy.v1.PharmacyGetIDRequest
	(*PharmacyGetIDResponse)(nil),                // 6: pharmacy.v1.PharmacyGetIDResponse
	(*GetAllPharmaciesRequest)(nil),              // 7: pharmacy.v1.GetAllPharmaciesRequest
	(*GetAllPharmaciesResponse)(nil),             // 8: pharmacy.v1.GetAllPharmaciesResponse
	(*UpdatePharmacyRequest)(nil),                // 9: pharmacy.v1.UpdatePharmacyRequest
	(*UpdatePharmacyResponse)(nil),               // 10: pharmacy.v1.UpdatePharmacyResponse
	(*PharmacyUpdateProfilePictureRequest)(nil),  // 11: pharmacy.v1.PharmacyUpdateProfilePictureRequest
	(*PharmacyUpdateProfilePictureResponse)(nil), // 12: pharmacy.v1.PharmacyUpdateProfilePictureResponse
	(*PharmacyUpdateProfileBannerRequest)(nil),   // 13: pharmacy.v1.PharmacyUpdateProfileBannerRequest
	(*PharmacyUpdateProfileBannerResponse)(nil),  // 14: pharmacy.v1.PharmacyUpdateProfileBannerResponse
	(*timestamppb.Timestamp)(nil),                // 15: google.protobuf.Timestamp
	(*Sorter)(nil),                               // 16: sorter.v1.Sorter
	(*emptypb.Empty)(nil),                        // 17: google.protobuf.Empty
}
var file_v1_pharmacy_api_proto_depIdxs = []int32{
	15, // 0: pharmacy.v1.Pharmacy.verified_at:type_name -> google.protobuf.Timestamp
	15, // 1: pharmacy.v1.Pharmacy.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: pharmacy.v1.Pharmacy.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: pharmacy.v1.PharmacySummary.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: pharmacy.v1.PharmacySummary.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: pharmacy.v1.CreatePharmacyResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	0,  // 6: pharmacy.v1.PharmacyGetMeResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	16, // 7: pharmacy.v1.GetAllPharmaciesRequest.by_location:type_name -> sorter.v1.Sorter
	16, // 8: pharmacy.v1.GetAllPharmaciesRequest.by_created_at:type_name -> sorter.v1.Sorter
	16, // 9: pharmacy.v1.GetAllPharmaciesRequest.by_updated_at:type_name -> sorter.v1.Sorter
	1,  // 10: pharmacy.v1.GetAllPharmaciesResponse.pharmacies:type_name -> pharmacy.v1.PharmacySummary
	0,  // 11: pharmacy.v1.UpdatePharmacyResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	0,  // 12: pharmacy.v1.PharmacyUpdateProfilePictureResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	0,  // 13: pharmacy.v1.PharmacyUpdateProfileBannerResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	2,  // 14: pharmacy.v1.PharmacyService.CreatePharmacy:input_type -> pharmacy.v1.CreatePharmacyRequest
	17, // 15: pharmacy.v1.PharmacyService.GetMe:input_type -> google.protobuf.Empty
	5,  // 16: pharmacy.v1.PharmacyService.GetID:input_type -> pharmacy.v1.PharmacyGetIDRequest
	7,  // 17: pharmacy.v1.PharmacyService.GetAllPharmacies:input_type -> pharmacy.v1.GetAllPharmaciesRequest
	9,  // 18: pharmacy.v1.PharmacyService.UpdatePharmacy:input_type -> pharmacy.v1.UpdatePharmacyRequest
	11, // 19: pharmacy.v1.PharmacyService.UpdateProfilePicture:input_type -> pharmacy.v1.PharmacyUpdateProfilePictureRequest
	13, // 20: pharmacy.v1.PharmacyService.UpdateProfileBanner:input_type -> pharmacy.v1.PharmacyUpdateProfileBannerRequest
	3,  // 21: pharmacy.v1.PharmacyService.CreatePharmacy:output_type -> pharmacy.v1.CreatePharmacyResponse
	4,  // 22: pharmacy.v1.PharmacyService.GetMe:output_type -> pharmacy.v1.PharmacyGetMeResponse
	6,  // 23: pharmacy.v1.PharmacyService.GetID:output_type -> pharmacy.v1.PharmacyGetIDResponse
	8,  // 24: pharmacy.v1.PharmacyService.GetAllPharmacies:output_type -> pharmacy.v1.GetAllPharmaciesResponse
	10, // 25: pharmacy.v1.PharmacyService.UpdatePharmacy:output_type -> pharmacy.v1.UpdatePharmacyResponse
	12, // 26: pharmacy.v1.PharmacyService.UpdateProfilePicture:output_type -> pharmacy.v1.PharmacyUpdateProfilePictureResponse
	14, // 27: pharmacy.v1.PharmacyService.UpdateProfileBanner:output_type -> pharmacy.v1.PharmacyUpdateProfileBannerResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_v1_pharmacy_api_proto_init() }
func file_v1_pharmacy_api_proto_init() {
	if File_v1_pharmacy_api_proto != nil {
		return
	}
	file_v1_sorter_proto_init()
	file_v1_pharmacy_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_pharmacy_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_pharmacy_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_pharmacy_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_v1_pharmacy_api_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pharmacy_api_proto_rawDesc), len(file_v1_pharmacy_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_pharmacy_api_proto_goTypes,
		DependencyIndexes: file_v1_pharmacy_api_proto_depIdxs,
		MessageInfos:      file_v1_pharmacy_api_proto_msgTypes,
	}.Build()
	File_v1_pharmacy_api_proto = out.File
	file_v1_pharmacy_api_proto_goTypes = nil
	file_v1_pharmacy_api_proto_depIdxs = nil
}
