// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/pharmacy_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pharmacy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LegalName      *string                `protobuf:"bytes,3,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	OnlineHours    []byte                 `protobuf:"bytes,6,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	Country        string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1  *string                `protobuf:"bytes,8,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2  *string                `protobuf:"bytes,9,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3  *string                `protobuf:"bytes,10,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4  *string                `protobuf:"bytes,11,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street         string                 `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode     string                 `protobuf:"bytes,13,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude       float64                `protobuf:"fixed64,14,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,15,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Email          *string                `protobuf:"bytes,16,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone          *string                `protobuf:"bytes,17,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Website        *string                `protobuf:"bytes,18,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Whatsapp       *string                `protobuf:"bytes,19,opt,name=whatsapp,proto3,oneof" json:"whatsapp,omitempty"`
	ProfilePicture *string                `protobuf:"bytes,20,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	ProfileBanner  *string                `protobuf:"bytes,21,opt,name=profile_banner,json=profileBanner,proto3,oneof" json:"profile_banner,omitempty"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pharmacy) Reset() {
	*x = Pharmacy{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pharmacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pharmacy) ProtoMessage() {}

func (x *Pharmacy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pharmacy.ProtoReflect.Descriptor instead.
func (*Pharmacy) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{0}
}

func (x *Pharmacy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pharmacy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pharmacy) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *Pharmacy) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Pharmacy) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pharmacy) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *Pharmacy) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *Pharmacy) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *Pharmacy) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Pharmacy) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Pharmacy) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Pharmacy) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Pharmacy) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Pharmacy) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *Pharmacy) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *Pharmacy) GetWhatsapp() string {
	if x != nil && x.Whatsapp != nil {
		return *x.Whatsapp
	}
	return ""
}

func (x *Pharmacy) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *Pharmacy) GetProfileBanner() string {
	if x != nil && x.ProfileBanner != nil {
		return *x.ProfileBanner
	}
	return ""
}

func (x *Pharmacy) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Pharmacy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Pharmacy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePharmacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LegalName     *string                `protobuf:"bytes,2,opt,name=legal_name,json=legalName,proto3,oneof" json:"legal_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	OnlineHours   []byte                 `protobuf:"bytes,4,opt,name=online_hours,json=onlineHours,proto3,oneof" json:"online_hours,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *string                `protobuf:"bytes,6,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2 *string                `protobuf:"bytes,7,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3 *string                `protobuf:"bytes,8,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4 *string                `protobuf:"bytes,9,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,10,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode    string                 `protobuf:"bytes,11,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,13,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Email         *string                `protobuf:"bytes,14,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone         *string                `protobuf:"bytes,15,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Website       *string                `protobuf:"bytes,16,opt,name=website,proto3,oneof" json:"website,omitempty"`
	Whatsapp      *string                `protobuf:"bytes,17,opt,name=whatsapp,proto3,oneof" json:"whatsapp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePharmacyRequest) Reset() {
	*x = CreatePharmacyRequest{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePharmacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePharmacyRequest) ProtoMessage() {}

func (x *CreatePharmacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePharmacyRequest.ProtoReflect.Descriptor instead.
func (*CreatePharmacyRequest) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePharmacyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePharmacyRequest) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *CreatePharmacyRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePharmacyRequest) GetOnlineHours() []byte {
	if x != nil {
		return x.OnlineHours
	}
	return nil
}

func (x *CreatePharmacyRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *CreatePharmacyRequest) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *CreatePharmacyRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreatePharmacyRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreatePharmacyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePharmacyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreatePharmacyRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreatePharmacyRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreatePharmacyRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

func (x *CreatePharmacyRequest) GetWhatsapp() string {
	if x != nil && x.Whatsapp != nil {
		return *x.Whatsapp
	}
	return ""
}

type CreatePharmacyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePharmacyResponse) Reset() {
	*x = CreatePharmacyResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePharmacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePharmacyResponse) ProtoMessage() {}

func (x *CreatePharmacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePharmacyResponse.ProtoReflect.Descriptor instead.
func (*CreatePharmacyResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePharmacyResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

type PharmacyGetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pharmacy      *Pharmacy              `protobuf:"bytes,1,opt,name=pharmacy,proto3" json:"pharmacy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PharmacyGetMeResponse) Reset() {
	*x = PharmacyGetMeResponse{}
	mi := &file_v1_pharmacy_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PharmacyGetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PharmacyGetMeResponse) ProtoMessage() {}

func (x *PharmacyGetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_pharmacy_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PharmacyGetMeResponse.ProtoReflect.Descriptor instead.
func (*PharmacyGetMeResponse) Descriptor() ([]byte, []int) {
	return file_v1_pharmacy_api_proto_rawDescGZIP(), []int{3}
}

func (x *PharmacyGetMeResponse) GetPharmacy() *Pharmacy {
	if x != nil {
		return x.Pharmacy
	}
	return nil
}

var File_v1_pharmacy_api_proto protoreflect.FileDescriptor

const file_v1_pharmacy_api_proto_rawDesc = "" +
	"\n" +
	"\x15v1/pharmacy_api.proto\x12\vpharmacy.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\b\n" +
	"\bPharmacy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"legal_name\x18\x03 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12&\n" +
	"\fonline_hours\x18\x06 \x01(\fH\x02R\vonlineHours\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\b \x01(\tH\x03R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\t \x01(\tH\x04R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\n" +
	" \x01(\tH\x05R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\v \x01(\tH\x06R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\f \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\r \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x01R\tlongitude\x12\x19\n" +
	"\x05email\x18\x10 \x01(\tH\aR\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x11 \x01(\tH\bR\x05phone\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x12 \x01(\tH\tR\awebsite\x88\x01\x01\x12\x1f\n" +
	"\bwhatsapp\x18\x13 \x01(\tH\n" +
	"R\bwhatsapp\x88\x01\x01\x12,\n" +
	"\x0fprofile_picture\x18\x14 \x01(\tH\vR\x0eprofilePicture\x88\x01\x01\x12*\n" +
	"\x0eprofile_banner\x18\x15 \x01(\tH\fR\rprofileBanner\x88\x01\x01\x12;\n" +
	"\vverified_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x129\n" +
	"\n" +
	"created_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_legal_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_online_hoursB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_websiteB\v\n" +
	"\t_whatsappB\x12\n" +
	"\x10_profile_pictureB\x11\n" +
	"\x0f_profile_banner\"\xee\x05\n" +
	"\x15CreatePharmacyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"legal_name\x18\x02 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12&\n" +
	"\fonline_hours\x18\x04 \x01(\fH\x02R\vonlineHours\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\x06 \x01(\tH\x03R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\a \x01(\tH\x04R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\b \x01(\tH\x05R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\t \x01(\tH\x06R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\n" +
	" \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\v \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\f \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\r \x01(\x01R\tlongitude\x12\x19\n" +
	"\x05email\x18\x0e \x01(\tH\aR\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x0f \x01(\tH\bR\x05phone\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x10 \x01(\tH\tR\awebsite\x88\x01\x01\x12\x1f\n" +
	"\bwhatsapp\x18\x11 \x01(\tH\n" +
	"R\bwhatsapp\x88\x01\x01B\r\n" +
	"\v_legal_nameB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_online_hoursB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4B\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\n" +
	"\n" +
	"\b_websiteB\v\n" +
	"\t_whatsapp\"K\n" +
	"\x16CreatePharmacyResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy\"J\n" +
	"\x15PharmacyGetMeResponse\x121\n" +
	"\bpharmacy\x18\x01 \x01(\v2\x15.pharmacy.v1.PharmacyR\bpharmacy2\xb1\x01\n" +
	"\x0fPharmacyService\x12Y\n" +
	"\x0eCreatePharmacy\x12\".pharmacy.v1.CreatePharmacyRequest\x1a#.pharmacy.v1.CreatePharmacyResponse\x12C\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a\".pharmacy.v1.PharmacyGetMeResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_pharmacy_api_proto_rawDescOnce sync.Once
	file_v1_pharmacy_api_proto_rawDescData []byte
)

func file_v1_pharmacy_api_proto_rawDescGZIP() []byte {
	file_v1_pharmacy_api_proto_rawDescOnce.Do(func() {
		file_v1_pharmacy_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_pharmacy_api_proto_rawDesc), len(file_v1_pharmacy_api_proto_rawDesc)))
	})
	return file_v1_pharmacy_api_proto_rawDescData
}

var file_v1_pharmacy_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_pharmacy_api_proto_goTypes = []any{
	(*Pharmacy)(nil),               // 0: pharmacy.v1.Pharmacy
	(*CreatePharmacyRequest)(nil),  // 1: pharmacy.v1.CreatePharmacyRequest
	(*CreatePharmacyResponse)(nil), // 2: pharmacy.v1.CreatePharmacyResponse
	(*PharmacyGetMeResponse)(nil),  // 3: pharmacy.v1.PharmacyGetMeResponse
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_v1_pharmacy_api_proto_depIdxs = []int32{
	4, // 0: pharmacy.v1.Pharmacy.verified_at:type_name -> google.protobuf.Timestamp
	4, // 1: pharmacy.v1.Pharmacy.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: pharmacy.v1.Pharmacy.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: pharmacy.v1.CreatePharmacyResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	0, // 4: pharmacy.v1.PharmacyGetMeResponse.pharmacy:type_name -> pharmacy.v1.Pharmacy
	1, // 5: pharmacy.v1.PharmacyService.CreatePharmacy:input_type -> pharmacy.v1.CreatePharmacyRequest
	5, // 6: pharmacy.v1.PharmacyService.GetMe:input_type -> google.protobuf.Empty
	2, // 7: pharmacy.v1.PharmacyService.CreatePharmacy:output_type -> pharmacy.v1.CreatePharmacyResponse
	3, // 8: pharmacy.v1.PharmacyService.GetMe:output_type -> pharmacy.v1.PharmacyGetMeResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_pharmacy_api_proto_init() }
func file_v1_pharmacy_api_proto_init() {
	if File_v1_pharmacy_api_proto != nil {
		return
	}
	file_v1_pharmacy_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_pharmacy_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_pharmacy_api_proto_rawDesc), len(file_v1_pharmacy_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_pharmacy_api_proto_goTypes,
		DependencyIndexes: file_v1_pharmacy_api_proto_depIdxs,
		MessageInfos:      file_v1_pharmacy_api_proto_msgTypes,
	}.Build()
	File_v1_pharmacy_api_proto = out.File
	file_v1_pharmacy_api_proto_goTypes = nil
	file_v1_pharmacy_api_proto_depIdxs = nil
}
