// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: v1/pharmacy_api.proto

package apis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PharmacyService_CreatePharmacy_FullMethodName       = "/pharmacy.v1.PharmacyService/CreatePharmacy"
	PharmacyService_GetMe_FullMethodName                = "/pharmacy.v1.PharmacyService/GetMe"
	PharmacyService_GetID_FullMethodName                = "/pharmacy.v1.PharmacyService/GetID"
	PharmacyService_GetPharmacyByID_FullMethodName      = "/pharmacy.v1.PharmacyService/GetPharmacyByID"
	PharmacyService_GetAllPharmacies_FullMethodName     = "/pharmacy.v1.PharmacyService/GetAllPharmacies"
	PharmacyService_UpdatePharmacy_FullMethodName       = "/pharmacy.v1.PharmacyService/UpdatePharmacy"
	PharmacyService_UpdateProfilePicture_FullMethodName = "/pharmacy.v1.PharmacyService/UpdateProfilePicture"
	PharmacyService_UpdateProfileBanner_FullMethodName  = "/pharmacy.v1.PharmacyService/UpdateProfileBanner"
)

// PharmacyServiceClient is the client API for PharmacyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PharmacyServiceClient interface {
	CreatePharmacy(ctx context.Context, in *CreatePharmacyRequest, opts ...grpc.CallOption) (*CreatePharmacyResponse, error)
	GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PharmacyGetMeResponse, error)
	GetID(ctx context.Context, in *PharmacyGetIDRequest, opts ...grpc.CallOption) (*PharmacyGetIDResponse, error)
	GetPharmacyByID(ctx context.Context, in *GetPharmacyByIDRequest, opts ...grpc.CallOption) (*GetPharmacyByIDResponse, error)
	GetAllPharmacies(ctx context.Context, in *GetAllPharmaciesRequest, opts ...grpc.CallOption) (*GetAllPharmaciesResponse, error)
	UpdatePharmacy(ctx context.Context, in *UpdatePharmacyRequest, opts ...grpc.CallOption) (*UpdatePharmacyResponse, error)
	UpdateProfilePicture(ctx context.Context, in *PharmacyUpdateProfilePictureRequest, opts ...grpc.CallOption) (*PharmacyUpdateProfilePictureResponse, error)
	UpdateProfileBanner(ctx context.Context, in *PharmacyUpdateProfileBannerRequest, opts ...grpc.CallOption) (*PharmacyUpdateProfileBannerResponse, error)
}

type pharmacyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPharmacyServiceClient(cc grpc.ClientConnInterface) PharmacyServiceClient {
	return &pharmacyServiceClient{cc}
}

func (c *pharmacyServiceClient) CreatePharmacy(ctx context.Context, in *CreatePharmacyRequest, opts ...grpc.CallOption) (*CreatePharmacyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePharmacyResponse)
	err := c.cc.Invoke(ctx, PharmacyService_CreatePharmacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PharmacyGetMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PharmacyGetMeResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetID(ctx context.Context, in *PharmacyGetIDRequest, opts ...grpc.CallOption) (*PharmacyGetIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PharmacyGetIDResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetPharmacyByID(ctx context.Context, in *GetPharmacyByIDRequest, opts ...grpc.CallOption) (*GetPharmacyByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPharmacyByIDResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetPharmacyByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) GetAllPharmacies(ctx context.Context, in *GetAllPharmaciesRequest, opts ...grpc.CallOption) (*GetAllPharmaciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPharmaciesResponse)
	err := c.cc.Invoke(ctx, PharmacyService_GetAllPharmacies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) UpdatePharmacy(ctx context.Context, in *UpdatePharmacyRequest, opts ...grpc.CallOption) (*UpdatePharmacyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePharmacyResponse)
	err := c.cc.Invoke(ctx, PharmacyService_UpdatePharmacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) UpdateProfilePicture(ctx context.Context, in *PharmacyUpdateProfilePictureRequest, opts ...grpc.CallOption) (*PharmacyUpdateProfilePictureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PharmacyUpdateProfilePictureResponse)
	err := c.cc.Invoke(ctx, PharmacyService_UpdateProfilePicture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pharmacyServiceClient) UpdateProfileBanner(ctx context.Context, in *PharmacyUpdateProfileBannerRequest, opts ...grpc.CallOption) (*PharmacyUpdateProfileBannerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PharmacyUpdateProfileBannerResponse)
	err := c.cc.Invoke(ctx, PharmacyService_UpdateProfileBanner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PharmacyServiceServer is the server API for PharmacyService service.
// All implementations must embed UnimplementedPharmacyServiceServer
// for forward compatibility.
type PharmacyServiceServer interface {
	CreatePharmacy(context.Context, *CreatePharmacyRequest) (*CreatePharmacyResponse, error)
	GetMe(context.Context, *emptypb.Empty) (*PharmacyGetMeResponse, error)
	GetID(context.Context, *PharmacyGetIDRequest) (*PharmacyGetIDResponse, error)
	GetPharmacyByID(context.Context, *GetPharmacyByIDRequest) (*GetPharmacyByIDResponse, error)
	GetAllPharmacies(context.Context, *GetAllPharmaciesRequest) (*GetAllPharmaciesResponse, error)
	UpdatePharmacy(context.Context, *UpdatePharmacyRequest) (*UpdatePharmacyResponse, error)
	UpdateProfilePicture(context.Context, *PharmacyUpdateProfilePictureRequest) (*PharmacyUpdateProfilePictureResponse, error)
	UpdateProfileBanner(context.Context, *PharmacyUpdateProfileBannerRequest) (*PharmacyUpdateProfileBannerResponse, error)
	mustEmbedUnimplementedPharmacyServiceServer()
}

// UnimplementedPharmacyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPharmacyServiceServer struct{}

func (UnimplementedPharmacyServiceServer) CreatePharmacy(context.Context, *CreatePharmacyRequest) (*CreatePharmacyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePharmacy not implemented")
}
func (UnimplementedPharmacyServiceServer) GetMe(context.Context, *emptypb.Empty) (*PharmacyGetMeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedPharmacyServiceServer) GetID(context.Context, *PharmacyGetIDRequest) (*PharmacyGetIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedPharmacyServiceServer) GetPharmacyByID(context.Context, *GetPharmacyByIDRequest) (*GetPharmacyByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPharmacyByID not implemented")
}
func (UnimplementedPharmacyServiceServer) GetAllPharmacies(context.Context, *GetAllPharmaciesRequest) (*GetAllPharmaciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPharmacies not implemented")
}
func (UnimplementedPharmacyServiceServer) UpdatePharmacy(context.Context, *UpdatePharmacyRequest) (*UpdatePharmacyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePharmacy not implemented")
}
func (UnimplementedPharmacyServiceServer) UpdateProfilePicture(context.Context, *PharmacyUpdateProfilePictureRequest) (*PharmacyUpdateProfilePictureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfilePicture not implemented")
}
func (UnimplementedPharmacyServiceServer) UpdateProfileBanner(context.Context, *PharmacyUpdateProfileBannerRequest) (*PharmacyUpdateProfileBannerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileBanner not implemented")
}
func (UnimplementedPharmacyServiceServer) mustEmbedUnimplementedPharmacyServiceServer() {}
func (UnimplementedPharmacyServiceServer) testEmbeddedByValue()                         {}

// UnsafePharmacyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PharmacyServiceServer will
// result in compilation errors.
type UnsafePharmacyServiceServer interface {
	mustEmbedUnimplementedPharmacyServiceServer()
}

func RegisterPharmacyServiceServer(s grpc.ServiceRegistrar, srv PharmacyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPharmacyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PharmacyService_ServiceDesc, srv)
}

func _PharmacyService_CreatePharmacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePharmacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).CreatePharmacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_CreatePharmacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).CreatePharmacy(ctx, req.(*CreatePharmacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetMe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PharmacyGetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetID(ctx, req.(*PharmacyGetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetPharmacyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPharmacyByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetPharmacyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetPharmacyByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetPharmacyByID(ctx, req.(*GetPharmacyByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_GetAllPharmacies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPharmaciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).GetAllPharmacies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_GetAllPharmacies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).GetAllPharmacies(ctx, req.(*GetAllPharmaciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_UpdatePharmacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePharmacyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).UpdatePharmacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_UpdatePharmacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).UpdatePharmacy(ctx, req.(*UpdatePharmacyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_UpdateProfilePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PharmacyUpdateProfilePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).UpdateProfilePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_UpdateProfilePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).UpdateProfilePicture(ctx, req.(*PharmacyUpdateProfilePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PharmacyService_UpdateProfileBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PharmacyUpdateProfileBannerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PharmacyServiceServer).UpdateProfileBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PharmacyService_UpdateProfileBanner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PharmacyServiceServer).UpdateProfileBanner(ctx, req.(*PharmacyUpdateProfileBannerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PharmacyService_ServiceDesc is the grpc.ServiceDesc for PharmacyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PharmacyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pharmacy.v1.PharmacyService",
	HandlerType: (*PharmacyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePharmacy",
			Handler:    _PharmacyService_CreatePharmacy_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _PharmacyService_GetMe_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _PharmacyService_GetID_Handler,
		},
		{
			MethodName: "GetPharmacyByID",
			Handler:    _PharmacyService_GetPharmacyByID_Handler,
		},
		{
			MethodName: "GetAllPharmacies",
			Handler:    _PharmacyService_GetAllPharmacies_Handler,
		},
		{
			MethodName: "UpdatePharmacy",
			Handler:    _PharmacyService_UpdatePharmacy_Handler,
		},
		{
			MethodName: "UpdateProfilePicture",
			Handler:    _PharmacyService_UpdateProfilePicture_Handler,
		},
		{
			MethodName: "UpdateProfileBanner",
			Handler:    _PharmacyService_UpdateProfileBanner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/pharmacy_api.proto",
}
