// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/product_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PharmacyId     string                 `protobuf:"bytes,2,opt,name=pharmacy_id,json=pharmacyId,proto3" json:"pharmacy_id,omitempty"`
	BrandName      string                 `protobuf:"bytes,3,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	GenericName    string                 `protobuf:"bytes,4,opt,name=generic_name,json=genericName,proto3" json:"generic_name,omitempty"`
	Description    *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RequiresRx     bool                   `protobuf:"varint,6,opt,name=requires_rx,json=requiresRx,proto3" json:"requires_rx,omitempty"`
	DosageForm     string                 `protobuf:"bytes,7,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	Strength       *string                `protobuf:"bytes,8,opt,name=strength,proto3,oneof" json:"strength,omitempty"`
	PackUnit       string                 `protobuf:"bytes,9,opt,name=pack_unit,json=packUnit,proto3" json:"pack_unit,omitempty"`
	PackSize       int32                  `protobuf:"varint,10,opt,name=pack_size,json=packSize,proto3" json:"pack_size,omitempty"`
	HeightCm       float64                `protobuf:"fixed64,11,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	LengthCm       float64                `protobuf:"fixed64,12,opt,name=length_cm,json=lengthCm,proto3" json:"length_cm,omitempty"`
	WidthCm        float64                `protobuf:"fixed64,13,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	WeightG        float64                `protobuf:"fixed64,14,opt,name=weight_g,json=weightG,proto3" json:"weight_g,omitempty"`
	Price          string                 `protobuf:"bytes,15,opt,name=price,proto3" json:"price,omitempty"`
	Currency       string                 `protobuf:"bytes,16,opt,name=currency,proto3" json:"currency,omitempty"`
	Quantity       int32                  `protobuf:"varint,17,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive       bool                   `protobuf:"varint,18,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ManufacturedBy string                 `protobuf:"bytes,19,opt,name=manufactured_by,json=manufacturedBy,proto3" json:"manufactured_by,omitempty"`
	ManufacturedIn string                 `protobuf:"bytes,20,opt,name=manufactured_in,json=manufacturedIn,proto3" json:"manufactured_in,omitempty"`
	RegAuthority   string                 `protobuf:"bytes,21,opt,name=reg_authority,json=regAuthority,proto3" json:"reg_authority,omitempty"`
	RegIdentifier  string                 `protobuf:"bytes,22,opt,name=reg_identifier,json=regIdentifier,proto3" json:"reg_identifier,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_v1_product_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_v1_product_api_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetPharmacyId() string {
	if x != nil {
		return x.PharmacyId
	}
	return ""
}

func (x *Product) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *Product) GetGenericName() string {
	if x != nil {
		return x.GenericName
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Product) GetRequiresRx() bool {
	if x != nil {
		return x.RequiresRx
	}
	return false
}

func (x *Product) GetDosageForm() string {
	if x != nil {
		return x.DosageForm
	}
	return ""
}

func (x *Product) GetStrength() string {
	if x != nil && x.Strength != nil {
		return *x.Strength
	}
	return ""
}

func (x *Product) GetPackUnit() string {
	if x != nil {
		return x.PackUnit
	}
	return ""
}

func (x *Product) GetPackSize() int32 {
	if x != nil {
		return x.PackSize
	}
	return 0
}

func (x *Product) GetHeightCm() float64 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *Product) GetLengthCm() float64 {
	if x != nil {
		return x.LengthCm
	}
	return 0
}

func (x *Product) GetWidthCm() float64 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *Product) GetWeightG() float64 {
	if x != nil {
		return x.WeightG
	}
	return 0
}

func (x *Product) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetManufacturedBy() string {
	if x != nil {
		return x.ManufacturedBy
	}
	return ""
}

func (x *Product) GetManufacturedIn() string {
	if x != nil {
		return x.ManufacturedIn
	}
	return ""
}

func (x *Product) GetRegAuthority() string {
	if x != nil {
		return x.RegAuthority
	}
	return ""
}

func (x *Product) GetRegIdentifier() string {
	if x != nil {
		return x.RegIdentifier
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProductRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BrandName      string                 `protobuf:"bytes,1,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	GenericName    string                 `protobuf:"bytes,2,opt,name=generic_name,json=genericName,proto3" json:"generic_name,omitempty"`
	Description    *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	RequiresRx     bool                   `protobuf:"varint,4,opt,name=requires_rx,json=requiresRx,proto3" json:"requires_rx,omitempty"`
	DosageForm     string                 `protobuf:"bytes,5,opt,name=dosage_form,json=dosageForm,proto3" json:"dosage_form,omitempty"`
	Strength       *string                `protobuf:"bytes,6,opt,name=strength,proto3,oneof" json:"strength,omitempty"`
	PackUnit       string                 `protobuf:"bytes,7,opt,name=pack_unit,json=packUnit,proto3" json:"pack_unit,omitempty"`
	PackSize       int32                  `protobuf:"varint,8,opt,name=pack_size,json=packSize,proto3" json:"pack_size,omitempty"`
	HeightCm       float64                `protobuf:"fixed64,9,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	LengthCm       float64                `protobuf:"fixed64,10,opt,name=length_cm,json=lengthCm,proto3" json:"length_cm,omitempty"`
	WidthCm        float64                `protobuf:"fixed64,11,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	WeightG        float64                `protobuf:"fixed64,12,opt,name=weight_g,json=weightG,proto3" json:"weight_g,omitempty"`
	Price          string                 `protobuf:"bytes,13,opt,name=price,proto3" json:"price,omitempty"`
	Currency       string                 `protobuf:"bytes,14,opt,name=currency,proto3" json:"currency,omitempty"`
	Quantity       int32                  `protobuf:"varint,15,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsActive       bool                   `protobuf:"varint,16,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ManufacturedBy string                 `protobuf:"bytes,17,opt,name=manufactured_by,json=manufacturedBy,proto3" json:"manufactured_by,omitempty"`
	ManufacturedIn string                 `protobuf:"bytes,18,opt,name=manufactured_in,json=manufacturedIn,proto3" json:"manufactured_in,omitempty"`
	RegAuthority   string                 `protobuf:"bytes,19,opt,name=reg_authority,json=regAuthority,proto3" json:"reg_authority,omitempty"`
	RegIdentifier  string                 `protobuf:"bytes,20,opt,name=reg_identifier,json=regIdentifier,proto3" json:"reg_identifier,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_v1_product_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_v1_product_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *CreateProductRequest) GetGenericName() string {
	if x != nil {
		return x.GenericName
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetRequiresRx() bool {
	if x != nil {
		return x.RequiresRx
	}
	return false
}

func (x *CreateProductRequest) GetDosageForm() string {
	if x != nil {
		return x.DosageForm
	}
	return ""
}

func (x *CreateProductRequest) GetStrength() string {
	if x != nil && x.Strength != nil {
		return *x.Strength
	}
	return ""
}

func (x *CreateProductRequest) GetPackUnit() string {
	if x != nil {
		return x.PackUnit
	}
	return ""
}

func (x *CreateProductRequest) GetPackSize() int32 {
	if x != nil {
		return x.PackSize
	}
	return 0
}

func (x *CreateProductRequest) GetHeightCm() float64 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *CreateProductRequest) GetLengthCm() float64 {
	if x != nil {
		return x.LengthCm
	}
	return 0
}

func (x *CreateProductRequest) GetWidthCm() float64 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *CreateProductRequest) GetWeightG() float64 {
	if x != nil {
		return x.WeightG
	}
	return 0
}

func (x *CreateProductRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateProductRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateProductRequest) GetManufacturedBy() string {
	if x != nil {
		return x.ManufacturedBy
	}
	return ""
}

func (x *CreateProductRequest) GetManufacturedIn() string {
	if x != nil {
		return x.ManufacturedIn
	}
	return ""
}

func (x *CreateProductRequest) GetRegAuthority() string {
	if x != nil {
		return x.RegAuthority
	}
	return ""
}

func (x *CreateProductRequest) GetRegIdentifier() string {
	if x != nil {
		return x.RegIdentifier
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_v1_product_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_product_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_v1_product_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_v1_product_api_proto protoreflect.FileDescriptor

const file_v1_product_api_proto_rawDesc = "" +
	"\n" +
	"\x14v1/product_api.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x06\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpharmacy_id\x18\x02 \x01(\tR\n" +
	"pharmacyId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x03 \x01(\tR\tbrandName\x12!\n" +
	"\fgeneric_name\x18\x04 \x01(\tR\vgenericName\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vrequires_rx\x18\x06 \x01(\bR\n" +
	"requiresRx\x12\x1f\n" +
	"\vdosage_form\x18\a \x01(\tR\n" +
	"dosageForm\x12\x1f\n" +
	"\bstrength\x18\b \x01(\tH\x01R\bstrength\x88\x01\x01\x12\x1b\n" +
	"\tpack_unit\x18\t \x01(\tR\bpackUnit\x12\x1b\n" +
	"\tpack_size\x18\n" +
	" \x01(\x05R\bpackSize\x12\x1b\n" +
	"\theight_cm\x18\v \x01(\x01R\bheightCm\x12\x1b\n" +
	"\tlength_cm\x18\f \x01(\x01R\blengthCm\x12\x19\n" +
	"\bwidth_cm\x18\r \x01(\x01R\awidthCm\x12\x19\n" +
	"\bweight_g\x18\x0e \x01(\x01R\aweightG\x12\x14\n" +
	"\x05price\x18\x0f \x01(\tR\x05price\x12\x1a\n" +
	"\bcurrency\x18\x10 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bquantity\x18\x11 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tis_active\x18\x12 \x01(\bR\bisActive\x12'\n" +
	"\x0fmanufactured_by\x18\x13 \x01(\tR\x0emanufacturedBy\x12'\n" +
	"\x0fmanufactured_in\x18\x14 \x01(\tR\x0emanufacturedIn\x12#\n" +
	"\rreg_authority\x18\x15 \x01(\tR\fregAuthority\x12%\n" +
	"\x0ereg_identifier\x18\x16 \x01(\tR\rregIdentifier\x129\n" +
	"\n" +
	"created_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_strength\"\xb2\x05\n" +
	"\x14CreateProductRequest\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x01 \x01(\tR\tbrandName\x12!\n" +
	"\fgeneric_name\x18\x02 \x01(\tR\vgenericName\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vrequires_rx\x18\x04 \x01(\bR\n" +
	"requiresRx\x12\x1f\n" +
	"\vdosage_form\x18\x05 \x01(\tR\n" +
	"dosageForm\x12\x1f\n" +
	"\bstrength\x18\x06 \x01(\tH\x01R\bstrength\x88\x01\x01\x12\x1b\n" +
	"\tpack_unit\x18\a \x01(\tR\bpackUnit\x12\x1b\n" +
	"\tpack_size\x18\b \x01(\x05R\bpackSize\x12\x1b\n" +
	"\theight_cm\x18\t \x01(\x01R\bheightCm\x12\x1b\n" +
	"\tlength_cm\x18\n" +
	" \x01(\x01R\blengthCm\x12\x19\n" +
	"\bwidth_cm\x18\v \x01(\x01R\awidthCm\x12\x19\n" +
	"\bweight_g\x18\f \x01(\x01R\aweightG\x12\x14\n" +
	"\x05price\x18\r \x01(\tR\x05price\x12\x1a\n" +
	"\bcurrency\x18\x0e \x01(\tR\bcurrency\x12\x1a\n" +
	"\bquantity\x18\x0f \x01(\x05R\bquantity\x12\x1b\n" +
	"\tis_active\x18\x10 \x01(\bR\bisActive\x12'\n" +
	"\x0fmanufactured_by\x18\x11 \x01(\tR\x0emanufacturedBy\x12'\n" +
	"\x0fmanufactured_in\x18\x12 \x01(\tR\x0emanufacturedIn\x12#\n" +
	"\rreg_authority\x18\x13 \x01(\tR\fregAuthority\x12%\n" +
	"\x0ereg_identifier\x18\x14 \x01(\tR\rregIdentifierB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_strength\"F\n" +
	"\x15CreateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct2f\n" +
	"\x0eProductService\x12T\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_product_api_proto_rawDescOnce sync.Once
	file_v1_product_api_proto_rawDescData []byte
)

func file_v1_product_api_proto_rawDescGZIP() []byte {
	file_v1_product_api_proto_rawDescOnce.Do(func() {
		file_v1_product_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_product_api_proto_rawDesc), len(file_v1_product_api_proto_rawDesc)))
	})
	return file_v1_product_api_proto_rawDescData
}

var file_v1_product_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_product_api_proto_goTypes = []any{
	(*Product)(nil),               // 0: product.v1.Product
	(*CreateProductRequest)(nil),  // 1: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 2: product.v1.CreateProductResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_product_api_proto_depIdxs = []int32{
	3, // 0: product.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: product.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: product.v1.CreateProductResponse.product:type_name -> product.v1.Product
	1, // 3: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2, // 4: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_product_api_proto_init() }
func file_v1_product_api_proto_init() {
	if File_v1_product_api_proto != nil {
		return
	}
	file_v1_product_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_product_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_product_api_proto_rawDesc), len(file_v1_product_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_product_api_proto_goTypes,
		DependencyIndexes: file_v1_product_api_proto_depIdxs,
		MessageInfos:      file_v1_product_api_proto_msgTypes,
	}.Build()
	File_v1_product_api_proto = out.File
	file_v1_product_api_proto_goTypes = nil
	file_v1_product_api_proto_depIdxs = nil
}
