// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/user_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sex            *string                `protobuf:"bytes,3,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Birthdate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Phone          *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	ProfilePicture *string                `protobuf:"bytes,6,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
	ProfileBanner  *string                `protobuf:"bytes,7,opt,name=profile_banner,json=profileBanner,proto3,oneof" json:"profile_banner,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *User) GetBirthdate() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetProfilePicture() string {
	if x != nil && x.ProfilePicture != nil {
		return *x.ProfilePicture
	}
	return ""
}

func (x *User) GetProfileBanner() string {
	if x != nil && x.ProfileBanner != nil {
		return *x.ProfileBanner
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex           *string                `protobuf:"bytes,2,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Birthdate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	Phone         *string                `protobuf:"bytes,4,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_v1_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *CreateUserRequest) GetBirthdate() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthdate
	}
	return nil
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_v1_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_v1_user_api_proto protoreflect.FileDescriptor

const file_v1_user_api_proto_rawDesc = "" +
	"\n" +
	"\x11v1/user_api.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x03sex\x18\x03 \x01(\tH\x00R\x03sex\x88\x01\x01\x128\n" +
	"\tbirthdate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x01R\x05phone\x88\x01\x01\x12,\n" +
	"\x0fprofile_picture\x18\x06 \x01(\tH\x02R\x0eprofilePicture\x88\x01\x01\x12*\n" +
	"\x0eprofile_banner\x18\a \x01(\tH\x03R\rprofileBanner\x88\x01\x01B\x06\n" +
	"\x04_sexB\b\n" +
	"\x06_phoneB\x12\n" +
	"\x10_profile_pictureB\x11\n" +
	"\x0f_profile_banner\"\xa5\x01\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x03sex\x18\x02 \x01(\tH\x00R\x03sex\x88\x01\x01\x128\n" +
	"\tbirthdate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tbirthdate\x12\x19\n" +
	"\x05phone\x18\x04 \x01(\tH\x01R\x05phone\x88\x01\x01B\x06\n" +
	"\x04_sexB\b\n" +
	"\x06_phone\"7\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user2T\n" +
	"\vUserService\x12E\n" +
	"\n" +
	"CreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_user_api_proto_rawDescOnce sync.Once
	file_v1_user_api_proto_rawDescData []byte
)

func file_v1_user_api_proto_rawDescGZIP() []byte {
	file_v1_user_api_proto_rawDescOnce.Do(func() {
		file_v1_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)))
	})
	return file_v1_user_api_proto_rawDescData
}

var file_v1_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_user_api_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.v1.User
	(*CreateUserRequest)(nil),     // 1: user.v1.CreateUserRequest
	(*CreateUserResponse)(nil),    // 2: user.v1.CreateUserResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1_user_api_proto_depIdxs = []int32{
	3, // 0: user.v1.User.birthdate:type_name -> google.protobuf.Timestamp
	3, // 1: user.v1.CreateUserRequest.birthdate:type_name -> google.protobuf.Timestamp
	0, // 2: user.v1.CreateUserResponse.user:type_name -> user.v1.User
	1, // 3: user.v1.UserService.CreateUser:input_type -> user.v1.CreateUserRequest
	2, // 4: user.v1.UserService.CreateUser:output_type -> user.v1.CreateUserResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_user_api_proto_init() }
func file_v1_user_api_proto_init() {
	if File_v1_user_api_proto != nil {
		return
	}
	file_v1_user_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_api_proto_rawDesc), len(file_v1_user_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_api_proto_goTypes,
		DependencyIndexes: file_v1_user_api_proto_depIdxs,
		MessageInfos:      file_v1_user_api_proto_msgTypes,
	}.Build()
	File_v1_user_api_proto = out.File
	file_v1_user_api_proto_goTypes = nil
	file_v1_user_api_proto_depIdxs = nil
}
