// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: v1/user_address_api.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Notes         *string                `protobuf:"bytes,5,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,6,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Country       string                 `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *string                `protobuf:"bytes,8,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2 *string                `protobuf:"bytes,9,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3 *string                `protobuf:"bytes,10,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4 *string                `protobuf:"bytes,11,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,12,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode    string                 `protobuf:"bytes,13,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,14,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,15,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_v1_user_address_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Address) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Address) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Address) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Address) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *Address) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *Address) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *Address) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Notes         *string                `protobuf:"bytes,4,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Subdivision_1 *string                `protobuf:"bytes,7,opt,name=subdivision_1,json=subdivision1,proto3,oneof" json:"subdivision_1,omitempty"`
	Subdivision_2 *string                `protobuf:"bytes,8,opt,name=subdivision_2,json=subdivision2,proto3,oneof" json:"subdivision_2,omitempty"`
	Subdivision_3 *string                `protobuf:"bytes,9,opt,name=subdivision_3,json=subdivision3,proto3,oneof" json:"subdivision_3,omitempty"`
	Subdivision_4 *string                `protobuf:"bytes,10,opt,name=subdivision_4,json=subdivision4,proto3,oneof" json:"subdivision_4,omitempty"`
	Street        string                 `protobuf:"bytes,11,opt,name=street,proto3" json:"street,omitempty"`
	PostalCode    string                 `protobuf:"bytes,12,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,13,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,14,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_v1_user_address_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateAddressRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *CreateAddressRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAddressRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *CreateAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdivision_1() string {
	if x != nil && x.Subdivision_1 != nil {
		return *x.Subdivision_1
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdivision_2() string {
	if x != nil && x.Subdivision_2 != nil {
		return *x.Subdivision_2
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdivision_3() string {
	if x != nil && x.Subdivision_3 != nil {
		return *x.Subdivision_3
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdivision_4() string {
	if x != nil && x.Subdivision_4 != nil {
		return *x.Subdivision_4
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CreateAddressRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateAddressRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_v1_user_address_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetAllAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAddressesRequest) Reset() {
	*x = GetAllAddressesRequest{}
	mi := &file_v1_user_address_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAddressesRequest) ProtoMessage() {}

func (x *GetAllAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAllAddressesRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllAddressesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllAddressesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAddressesResponse) Reset() {
	*x = GetAllAddressesResponse{}
	mi := &file_v1_user_address_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAddressesResponse) ProtoMessage() {}

func (x *GetAllAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAllAddressesResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllAddressesResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *GetAllAddressesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetPrimaryAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     uint64                 `protobuf:"varint,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrimaryAddressRequest) Reset() {
	*x = SetPrimaryAddressRequest{}
	mi := &file_v1_user_address_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryAddressRequest) ProtoMessage() {}

func (x *SetPrimaryAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryAddressRequest.ProtoReflect.Descriptor instead.
func (*SetPrimaryAddressRequest) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{5}
}

func (x *SetPrimaryAddressRequest) GetAddressId() uint64 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type SetPrimaryAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrimaryAddressResponse) Reset() {
	*x = SetPrimaryAddressResponse{}
	mi := &file_v1_user_address_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrimaryAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrimaryAddressResponse) ProtoMessage() {}

func (x *SetPrimaryAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_user_address_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrimaryAddressResponse.ProtoReflect.Descriptor instead.
func (*SetPrimaryAddressResponse) Descriptor() ([]byte, []int) {
	return file_v1_user_address_api_proto_rawDescGZIP(), []int{6}
}

func (x *SetPrimaryAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_v1_user_address_api_proto protoreflect.FileDescriptor

const file_v1_user_address_api_proto_rawDesc = "" +
	"\n" +
	"\x19v1/user_address_api.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x05\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1c\n" +
	"\trecipient\x18\x03 \x01(\tR\trecipient\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x19\n" +
	"\x05notes\x18\x05 \x01(\tH\x00R\x05notes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x06 \x01(\bR\tisPrimary\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\b \x01(\tH\x01R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\t \x01(\tH\x02R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\n" +
	" \x01(\tH\x03R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\v \x01(\tH\x04R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\f \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\r \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x01R\tlongitude\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06_notesB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4\"\xa1\x04\n" +
	"\x14CreateAddressRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x19\n" +
	"\x05notes\x18\x04 \x01(\tH\x00R\x05notes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x05 \x01(\bR\tisPrimary\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12(\n" +
	"\rsubdivision_1\x18\a \x01(\tH\x01R\fsubdivision1\x88\x01\x01\x12(\n" +
	"\rsubdivision_2\x18\b \x01(\tH\x02R\fsubdivision2\x88\x01\x01\x12(\n" +
	"\rsubdivision_3\x18\t \x01(\tH\x03R\fsubdivision3\x88\x01\x01\x12(\n" +
	"\rsubdivision_4\x18\n" +
	" \x01(\tH\x04R\fsubdivision4\x88\x01\x01\x12\x16\n" +
	"\x06street\x18\v \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\f \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\r \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0e \x01(\x01R\tlongitudeB\b\n" +
	"\x06_notesB\x10\n" +
	"\x0e_subdivision_1B\x10\n" +
	"\x0e_subdivision_2B\x10\n" +
	"\x0e_subdivision_3B\x10\n" +
	"\x0e_subdivision_4\"C\n" +
	"\x15CreateAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.user.v1.AddressR\aaddress\"I\n" +
	"\x16GetAllAddressesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"_\n" +
	"\x17GetAllAddressesResponse\x12.\n" +
	"\taddresses\x18\x01 \x03(\v2\x10.user.v1.AddressR\taddresses\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"9\n" +
	"\x18SetPrimaryAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\x04R\taddressId\"G\n" +
	"\x19SetPrimaryAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.user.v1.AddressR\aaddress2\x92\x02\n" +
	"\x0eAddressService\x12N\n" +
	"\rCreateAddress\x12\x1d.user.v1.CreateAddressRequest\x1a\x1e.user.v1.CreateAddressResponse\x12T\n" +
	"\x0fGetAllAddresses\x12\x1f.user.v1.GetAllAddressesRequest\x1a .user.v1.GetAllAddressesResponse\x12Z\n" +
	"\x11SetPrimaryAddress\x12!.user.v1.SetPrimaryAddressRequest\x1a\".user.v1.SetPrimaryAddressResponseBJZHgithub.com/ritchieridanko/apotekly/services/shared/contract/apis/v1;apisb\x06proto3"

var (
	file_v1_user_address_api_proto_rawDescOnce sync.Once
	file_v1_user_address_api_proto_rawDescData []byte
)

func file_v1_user_address_api_proto_rawDescGZIP() []byte {
	file_v1_user_address_api_proto_rawDescOnce.Do(func() {
		file_v1_user_address_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_user_address_api_proto_rawDesc), len(file_v1_user_address_api_proto_rawDesc)))
	})
	return file_v1_user_address_api_proto_rawDescData
}

var file_v1_user_address_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_user_address_api_proto_goTypes = []any{
	(*Address)(nil),                   // 0: user.v1.Address
	(*CreateAddressRequest)(nil),      // 1: user.v1.CreateAddressRequest
	(*CreateAddressResponse)(nil),     // 2: user.v1.CreateAddressResponse
	(*GetAllAddressesRequest)(nil),    // 3: user.v1.GetAllAddressesRequest
	(*GetAllAddressesResponse)(nil),   // 4: user.v1.GetAllAddressesResponse
	(*SetPrimaryAddressRequest)(nil),  // 5: user.v1.SetPrimaryAddressRequest
	(*SetPrimaryAddressResponse)(nil), // 6: user.v1.SetPrimaryAddressResponse
	(*timestamppb.Timestamp)(nil),     // 7: google.protobuf.Timestamp
}
var file_v1_user_address_api_proto_depIdxs = []int32{
	7, // 0: user.v1.Address.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: user.v1.Address.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: user.v1.CreateAddressResponse.address:type_name -> user.v1.Address
	0, // 3: user.v1.GetAllAddressesResponse.addresses:type_name -> user.v1.Address
	0, // 4: user.v1.SetPrimaryAddressResponse.address:type_name -> user.v1.Address
	1, // 5: user.v1.AddressService.CreateAddress:input_type -> user.v1.CreateAddressRequest
	3, // 6: user.v1.AddressService.GetAllAddresses:input_type -> user.v1.GetAllAddressesRequest
	5, // 7: user.v1.AddressService.SetPrimaryAddress:input_type -> user.v1.SetPrimaryAddressRequest
	2, // 8: user.v1.AddressService.CreateAddress:output_type -> user.v1.CreateAddressResponse
	4, // 9: user.v1.AddressService.GetAllAddresses:output_type -> user.v1.GetAllAddressesResponse
	6, // 10: user.v1.AddressService.SetPrimaryAddress:output_type -> user.v1.SetPrimaryAddressResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_user_address_api_proto_init() }
func file_v1_user_address_api_proto_init() {
	if File_v1_user_address_api_proto != nil {
		return
	}
	file_v1_user_address_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_user_address_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_user_address_api_proto_rawDesc), len(file_v1_user_address_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_user_address_api_proto_goTypes,
		DependencyIndexes: file_v1_user_address_api_proto_depIdxs,
		MessageInfos:      file_v1_user_address_api_proto_msgTypes,
	}.Build()
	File_v1_user_address_api_proto = out.File
	file_v1_user_address_api_proto_goTypes = nil
	file_v1_user_address_api_proto_depIdxs = nil
}
