app:
  name: "gateway-service"

client:
  host: "localhost"
  port: 3000

server:
  host: "localhost"
  port: 8080
  timeout:
    read: "5s"
    write: "5s"
    shutdown: "10s"

service:
  auth:
    name: "auth-service"
    host: "localhost"
    port: 50051
  pharmacy:
    name: "pharmacy-service"
    host: "localhost"
    port: 50053
  product:
    name: "product-service"
    host: "localhost"
    port: 50054
  user:
    name: "user-service"
    host: "localhost"
    port: 50052

tracer:
  host: "localhost"
  port: 4317

jwt:
  secret: ""
