app:
  name: "user-service"

server:
  host: "localhost"
  port: 50052
  timeout:
    shutdown: "10s"

database:
  host: "localhost"
  port: 5432
  user: ""
  pass: ""
  name: "apotekly_user_db"
  ssl_mode: "disable"
  max_conns: 5
  min_conns: 1
  max_conn_lifetime: "1h"
  max_conn_idle_time: "30m"

tracer:
  host: "localhost"
  port: 4317
